/**
 * PHASE 4.3 — SHAREABLE PATHWAY REPORT
 *
 * Builds a print-ready, plain-data snapshot of the citizen's support pathway,
 * suitable for taking to a bank branch, DIC office or CSC.
 *
 * Rules:
 *  - Reuses Phase 4.2 pathway output and Phase 3.1 match results as-is.
 *  - No new calculations, no AI, no invented scheme facts.
 *  - Every listed scheme keeps its official source and verification line.
 *  - No amount is presented as assured government assistance.
 */

import type { MatchResult } from '../../types/matching';
import type { UserProfile } from '../../types/user';
import type { SupportPathway } from '../../types/supportPathway';
import type { TrackedApplication } from '../../types/tracker';
import { formatLakhCrore } from '../business/fundingCalculator';
import { evaluateSchemeFreshness } from '../tracker/schemeFreshness';

export interface ReportLine {
  label: string;
  value: string;
}

export interface ReportSchemeEntry {
  schemeName: string;
  shortCode?: string;
  areaLabel: string;
  matchPercentage: number;
  matchStatusLabel: string;
  source?: string;
  sourceUrl?: string;
  lastVerified?: string;
  verificationLine: string;
}

export interface ReportChecklistItem {
  label: string;
  stateLabel: string;
  isMandatory: boolean;
}

export interface PathwayReport {
  generatedAt: string;
  lang: 'en' | 'hi';
  title: string;
  subtitle: string;
  /** Guidance shown above the sheet (hidden when printing). */
  printHint: string;
  profileLines: ReportLine[];
  journeyLine: ReportLine;
  priorityLabels: string[];
  nextAction: { title: string; reason: string; cta: string };
  readiness: { stateLabel: string; summary: string; checks: ReportLine[] };
  schemes: ReportSchemeEntry[];
  checklist: ReportChecklistItem[];
  fundingLines: ReportLine[];
  trackedLines: ReportLine[];
  disclaimers: string[];
}

const COPY = {
  en: {
    title: 'My Support Pathway',
    subtitle: 'Generated by Yojana Setu from your own profile and verified scheme records',
    printHint: 'Use your browser’s print dialog to save this as a PDF.',
    stage: 'Current business stage',
    primaryNeed: 'Primary support need',
    secondaryNeeds: 'Other support needs',
    state: 'State',
    businessType: 'Business type',
    category: 'Social category',
    age: 'Age',
    income: 'Annual income',
    notProvided: 'Not provided',
    projectCost: 'Estimated project cost',
    ownInvestment: 'Own investment',
    fundingGap: 'Estimated funding requirement',
    readiness: 'Application readiness',
    tracked: 'Applications being tracked',
    none: 'None yet',
    notRecorded: 'Not recorded',
    verifiedOn: 'Verified on',
    verificationUnavailable: 'Verification date unavailable — check official guidelines',
    disclaimers: [
      'This report is a preparation aid. It is not an application, approval or sanction.',
      'Funding figures are your own estimated requirement, not an assured government amount.',
      'Scheme details are taken from recorded official sources. Always confirm current terms on the official portal.',
      'Where information is shown as unknown, it means it has not been provided or verified — it is not a rejection.',
    ],
  },
  hi: {
    title: 'मेरा सहायता मार्ग',
    subtitle: 'योजना सेतु द्वारा आपकी प्रोफाइल और सत्यापित योजना रिकॉर्ड से तैयार',
    printHint: 'ब्राउज़र के प्रिंट विकल्प से PDF के रूप में सहेजें।',
    stage: 'वर्तमान व्यावसायिक चरण',
    primaryNeed: 'मुख्य सहायता आवश्यकता',
    secondaryNeeds: 'अन्य सहायता आवश्यकताएं',
    state: 'राज्य',
    businessType: 'व्यवसाय प्रकार',
    category: 'सामाजिक श्रेणी',
    age: 'आयु',
    income: 'वार्षिक आय',
    notProvided: 'नहीं दिया गया',
    projectCost: 'अनुमानित परियोजना लागत',
    ownInvestment: 'स्वयं का निवेश',
    fundingGap: 'अनुमानित वित्तीय आवश्यकता',
    readiness: 'आवेदन तैयारी',
    tracked: 'ट्रैक किए जा रहे आवेदन',
    none: 'अभी कोई नहीं',
    notRecorded: 'दर्ज नहीं',
    verifiedOn: 'सत्यापित',
    verificationUnavailable: 'सत्यापन तिथि अनुपलब्ध — आधिकारिक दिशानिर्देश देखें',
    disclaimers: [
      'यह रिपोर्ट केवल तैयारी में सहायक है। यह आवेदन, स्वीकृति या मंजूरी नहीं है।',
      'वित्तीय राशि आपकी अनुमानित आवश्यकता है, सरकार द्वारा सुनिश्चित राशि नहीं।',
      'योजना विवरण दर्ज आधिकारिक स्रोतों से लिये गये हैं। वर्तमान शर्तें आधिकारिक पोर्टल पर अवश्य जाँचें।',
      'जहाँ जानकारी अज्ञात दिखाई गई है, वह अस्वीकरण नहीं — केवल जानकारी उपलब्ध/सत्यापित नहीं है।',
    ],
  },
} as const;

const MATCH_STATUS_COPY = {
  en: {
    eligible: 'Matches your profile',
    'near-match': 'Close to qualifying',
    'low-match': 'Limited match',
  },
  hi: {
    eligible: 'आपकी प्रोमाइल से मेल',
    'near-match': 'योग्यता के निकट',
    'low-match': 'सीमित मेल',
  },
} as const;

const PREP_STATE_COPY = {
  en: {
    PREPARED: 'Prepared',
    NOT_PREPARED: 'Not prepared',
    UNKNOWN: 'Unknown',
    NOT_REQUIRED: 'Not required',
  },
  hi: {
    PREPARED: 'तैयार',
    NOT_PREPARED: 'तैयार नहीं',
    UNKNOWN: 'अज्ञात',
    NOT_REQUIRED: 'आवश्यक नहीं',
  },
} as const;

const readable = (value?: string): string =>
  value ? value.replace(/_/g, ' ').toLowerCase() : '';

/** Builds the printable report. Pure function — same inputs, same output. */
export const buildPathwayReport = (args: {
  profile: UserProfile | null;
  pathway: SupportPathway;
  matchResults: MatchResult[];
  applications?: TrackedApplication[];
  lang?: 'en' | 'hi';
  generatedAt?: string;
  today?: Date;
}): PathwayReport => {
  const lang = args.lang === 'hi' ? 'hi' : 'en';
  const t = COPY[lang];
  const isHi = lang === 'hi';
  const { profile, pathway } = args;
  const generatedAt = args.generatedAt || new Date().toISOString();
  const today = args.today || new Date(generatedAt);

  const profileLines: ReportLine[] = [
    { label: t.state, value: profile?.state || t.notProvided },
    { label: t.businessType, value: profile?.businessType || t.notProvided },
    { label: t.category, value: profile?.category || t.notProvided },
    {
      label: t.age,
      value: profile?.age !== undefined && profile.age !== null ? String(profile.age) : t.notProvided,
    },
    {
      label: t.income,
      value:
        profile?.annualIncome !== undefined && profile.annualIncome !== null
          ? formatLakhCrore(profile.annualIncome, lang)
          : t.notProvided,
    },
    {
      label: t.primaryNeed,
      value: pathway.primaryNeed ? readable(String(pathway.primaryNeed)) : t.notProvided,
    },
    {
      label: t.secondaryNeeds,
      value:
        pathway.secondaryNeeds.length > 0
          ? pathway.secondaryNeeds.map((need) => readable(String(need))).join(', ')
          : t.none,
    },
  ];

  const fundingLines: ReportLine[] = pathway.funding.hasFundingDetails
    ? [
        {
          label: t.projectCost,
          value: formatLakhCrore(pathway.funding.totalProjectCost, lang),
        },
        {
          label: t.ownInvestment,
          value: formatLakhCrore(pathway.funding.existingInvestment, lang),
        },
        { label: t.fundingGap, value: formatLakhCrore(pathway.funding.fundingGap, lang) },
      ]
    : [];

  const schemeIndex = new Map(args.matchResults.map((m) => [m.scheme.id, m]));

  const schemes: ReportSchemeEntry[] = [];
  pathway.supportStack.forEach((group) => {
    group.schemes.forEach((entry) => {
      const match = schemeIndex.get(entry.schemeId);
      const freshness = match ? evaluateSchemeFreshness(match.scheme, today) : null;
      const lastVerified = entry.provenance.lastVerified;

      schemes.push({
        schemeName: entry.schemeName,
        shortCode: entry.shortCode,
        areaLabel: isHi ? group.labelHi : group.labelEn,
        matchPercentage: entry.matchPercentage,
        matchStatusLabel:
          MATCH_STATUS_COPY[lang][entry.matchStatus as keyof typeof MATCH_STATUS_COPY['en']] ||
          readable(String(entry.matchStatus)),
        source: entry.provenance.source,
        sourceUrl: entry.provenance.sourceUrl,
        lastVerified,
        verificationLine: lastVerified
          ? `${t.verifiedOn} ${lastVerified}${
              freshness?.shouldRecheckOfficialSource
                ? ` — ${isHi ? freshness.labelHi : freshness.labelEn}`
                : ''
            }`
          : t.verificationUnavailable,
      });
    });
  });

  const checklist: ReportChecklistItem[] = pathway.preparationChecklist.items.map((item) => ({
    label: isHi ? item.labelHi : item.labelEn,
    stateLabel:
      PREP_STATE_COPY[lang][item.state as keyof typeof PREP_STATE_COPY['en']] ||
      readable(String(item.state)),
    isMandatory: Boolean(item.isMandatory),
  }));

  const trackedLines: ReportLine[] = (args.applications || []).map((application) => ({
    label: application.schemeName,
    value: application.appliedOn
      ? `${readable(application.status)} — ${application.appliedOn}`
      : readable(application.status) || t.notRecorded,
  }));

  return {
    generatedAt,
    lang,
    title: t.title,
    subtitle: t.subtitle,
    printHint: t.printHint,
    profileLines,
    journeyLine: {
      label: t.stage,
      value: isHi ? pathway.currentStageLabelHi : pathway.currentStageLabelEn,
    },
    priorityLabels: pathway.recommendedSupportAreas
      .slice(0, 5)
      .map((area) => (isHi ? area.labelHi : area.labelEn)),
    nextAction: {
      title: isHi ? pathway.nextBestAction.titleHi : pathway.nextBestAction.titleEn,
      reason: isHi ? pathway.nextBestAction.reasonHi : pathway.nextBestAction.reasonEn,
      cta: isHi ? pathway.nextBestAction.ctaLabelHi : pathway.nextBestAction.ctaLabelEn,
    },
    readiness: {
      stateLabel: isHi ? pathway.readiness.labelHi : pathway.readiness.labelEn,
      summary: isHi ? pathway.readiness.summaryHi : pathway.readiness.summaryEn,
      checks: pathway.readiness.checks.map((check) => ({
        label: isHi ? check.labelHi : check.labelEn,
        value: isHi ? check.detailHi : check.detailEn,
      })),
    },
    schemes,
    checklist,
    fundingLines,
    trackedLines,
    disclaimers: [...t.disclaimers],
  };
};
