/**
 * PHASE 4.3 — SHAREABLE PATHWAY REPORT
 *
 * Builds a print-ready, plain-data snapshot of the citizen's support pathway,
 * suitable for taking to a bank branch, DIC office or CSC.
 *
 * Rules:
 *  - Reuses Phase 4.2 pathway output and Phase 3.1 match results as-is.
 *  - No new calculations, no AI, no invented scheme facts.
 *  - Every listed scheme keeps its official source and verification line.
 *  - No amount is presented as assured government assistance.
 */

import type { MatchResult } from '../../types/matching';
import type { UserProfile } from '../../types/user';
import type { SupportPathway } from '../../types/supportPathway';
import type { TrackedApplication } from '../../types/tracker';
import type { Language } from '../../i18n/types';
import { resolveLocalizedPair } from '../../i18n/resolveLocalized';
import { formatLakhCrore } from '../business/fundingCalculator';
import { evaluateSchemeFreshness, getLocalizedFreshness } from '../tracker/schemeFreshness';
import { SUPPORT_NEEDS_LOCALIZED, LIFECYCLE_PHASES_LOCALIZED } from '../../i18n/formI18n';
import { getLocalizedPathwayAction } from '../../i18n/pathwayActionI18n';
import { getLocalizedReadiness, getLocalizedReadinessCheck } from '../business/supportPathway';

interface ReportLine {
  label: string;
  value: string;
}

interface ReportSchemeEntry {
  schemeName: string;
  shortCode?: string;
  areaLabel: string;
  matchPercentage: number;
  matchStatusLabel: string;
  source?: string;
  sourceUrl?: string;
  lastVerified?: string;
  verificationLine: string;
}

interface ReportChecklistItem {
  label: string;
  stateLabel: string;
  isMandatory: boolean;
}

interface PathwayReport {
  generatedAt: string;
  lang: Language;
  title: string;
  subtitle: string;
  /** Guidance shown above the sheet (hidden when printing). */
  printHint: string;
  profileLines: ReportLine[];
  journeyLine: ReportLine;
  priorityLabels: string[];
  nextAction: { title: string; reason: string; cta: string };
  readiness: { stateLabel: string; summary: string; checks: ReportLine[] };
  schemes: ReportSchemeEntry[];
  checklist: ReportChecklistItem[];
  fundingLines: ReportLine[];
  trackedLines: ReportLine[];
  disclaimers: string[];
}

const COPY: Record<Language, {
  title: string;
  subtitle: string;
  printHint: string;
  stage: string;
  primaryNeed: string;
  secondaryNeeds: string;
  state: string;
  businessType: string;
  category: string;
  age: string;
  income: string;
  notProvided: string;
  projectCost: string;
  ownInvestment: string;
  fundingGap: string;
  readiness: string;
  tracked: string;
  none: string;
  notRecorded: string;
  verifiedOn: string;
  verificationUnavailable: string;
  disclaimers: string[];
}> = {
  en: {
    title: 'My Support Pathway',
    subtitle: 'Generated by Yojana Setu from your own profile and verified scheme records',
    printHint: 'Use your browser’s print dialog to save this as a PDF.',
    stage: 'Current business stage',
    primaryNeed: 'Primary support need',
    secondaryNeeds: 'Other support needs',
    state: 'State',
    businessType: 'Business type',
    category: 'Social category',
    age: 'Age',
    income: 'Annual income',
    notProvided: 'Not provided',
    projectCost: 'Estimated project cost',
    ownInvestment: 'Own investment',
    fundingGap: 'Estimated funding requirement',
    readiness: 'Application readiness',
    tracked: 'Applications being tracked',
    none: 'None yet',
    notRecorded: 'Not recorded',
    verifiedOn: 'Verified on',
    verificationUnavailable: 'Verification date unavailable — check official guidelines',
    disclaimers: [
      'This report is a preparation aid. It is not an application, approval or sanction.',
      'Funding figures are your own estimated requirement, not an assured government amount.',
      'Scheme details are taken from recorded official sources. Always confirm current terms on the official portal.',
      'Where information is shown as unknown, it means it has not been provided or verified — it is not a rejection.',
    ],
  },
  hi: {
    title: 'मेरा सहायता मार्ग',
    subtitle: 'योजना सेतु द्वारा आपकी प्रोफाइल और सत्यापित योजना रिकॉर्ड से तैयार',
    printHint: 'ब्राउज़र के प्रिंट विकल्प से PDF के रूप में सहेजें।',
    stage: 'वर्तमान व्यावसायिक चरण',
    primaryNeed: 'मुख्य सहायता आवश्यकता',
    secondaryNeeds: 'अन्य सहायता आवश्यकताएं',
    state: 'राज्य',
    businessType: 'व्यवसाय प्रकार',
    category: 'सामाजिक श्रेणी',
    age: 'आयु',
    income: 'वार्षिक आय',
    notProvided: 'नहीं दिया गया',
    projectCost: 'अनुमानित परियोजना लागत',
    ownInvestment: 'स्वयं का निवेश',
    fundingGap: 'अनुमानित वित्तीय आवश्यकता',
    readiness: 'आवेदन तैयारी',
    tracked: 'ट्रैक किए जा रहे आवेदन',
    none: 'अभी कोई नहीं',
    notRecorded: 'दर्ज नहीं',
    verifiedOn: 'सत्यापित',
    verificationUnavailable: 'सत्यापन तिथि अनुपलब्ध — आधिकारिक दिशानिर्देश देखें',
    disclaimers: [
      'यह रिपोर्ट केवल तैयारी में सहायक है। यह आवेदन, स्वीकृति या मंजूरी नहीं है।',
      'वित्तीय राशि आपकी अनुमानित आवश्यकता है, सरकार द्वारा सुनिश्चित राशि नहीं।',
      'योजना विवरण दर्ज आधिकारिक स्रोतों से लिये गये हैं। वर्तमान शर्तें आधिकारिक पोर्टल पर अवश्य जाँचें।',
      'जहाँ जानकारी अज्ञात दिखाई गई है, वह अस्वीकरण नहीं — केवल जानकारी उपलब्ध/सत्यापित नहीं है।',
    ],
  },
  ta: {
    title: 'எனது உதவிப் பாதை',
    subtitle: 'உங்கள் சுயவிவரம் மற்றும் சரிபார்க்கப்பட்ட திட்டப் பதிவுகளிலிருந்து யோஜனா சேது மூலம் உருவாக்கப்பட்டது',
    printHint: 'இதை PDF ஆக சேமிக்க உங்கள் உலாவியின் அச்சு விருப்பத்தைப் பயன்படுத்தவும்.',
    stage: 'தற்போதைய வணிக நிலை',
    primaryNeed: 'முதன்மை உதவித் தேவை',
    secondaryNeeds: 'இதர உதவித் தேவைகள்',
    state: 'மாநிலம்',
    businessType: 'வணிக வகை',
    category: 'சமூகப் பிரிவு',
    age: 'வயது',
    income: 'ஆண்டு வருமானம்',
    notProvided: 'வழங்கப்படவில்லை',
    projectCost: 'மதிப்பிடப்பட்ட திட்டச் செலவு',
    ownInvestment: 'சொந்த முதலீடு',
    fundingGap: 'மதிப்பிடப்பட்ட நிதித் தேவை',
    readiness: 'விண்ணப்பத் தயார்நிலை',
    tracked: 'கண்காணிக்கப்படும் விண்ணப்பங்கள்',
    none: 'இன்னும் எதுவும் இல்லை',
    notRecorded: 'பதிவு செய்யப்படவில்லை',
    verifiedOn: 'சரிபார்க்கப்பட்டது',
    verificationUnavailable: 'சரிபார்ப்பு தேதி கிடைக்கவில்லை — அதிகாரப்பூர்வ வழிகாட்டுதல்களைப் பார்க்கவும்',
    disclaimers: [
      'இந்த அறிக்கை தயாரிப்பு உதவி மட்டுமே. இது விண்ணப்பம், ஒப்புதல் அல்லது அனுமதி அல்ல.',
      'நிதி புள்ளிவிவரங்கள் உங்கள் சொந்த மதிப்பீட்டு தேவை, உறுதி செய்யப்பட்ட அரசுத் தொகை அல்ல.',
      'திட்ட விவரங்கள் பதிவு செய்யப்பட்ட அதிகாரப்பூர்வ மூலங்களிலிருந்து எடுக்கப்பட்டுள்ளன. அதிகாரப்பூர்வ போர்ட்டலில் எப்போதும் தற்போதைய விதிமுறைகளை உறுதிப்படுத்தவும்.',
      'தகவல் தெரியவில்லை என்று காட்டப்படும் இடங்களில், அது வழங்கப்படவில்லை அல்லது சரிபார்க்கப்படவில்லை என்று பொருள் — இது நிராகரிப்பு அல்ல.',
    ],
  },
  te: {
    title: 'నా సహాయ మార్గం',
    subtitle: 'మీ ప్రొఫైల్ మరియు ధృవీకరించబడిన పథక రికార్డుల నుండి యోజనా సేతు ద్వారా రూపొందించబడింది',
    printHint: 'దీన్ని PDFగా సేవ్ చేయడానికి మీ బ్రౌజర్ ప్రింట్ ఎంపికను ఉపయోగించండి.',
    stage: 'ప్రస్తుత వ్యాపార దశ',
    primaryNeed: 'ప్రాథమిక మద్దతు అవసరం',
    secondaryNeeds: 'ఇతర మద్దతు అవసరాలు',
    state: 'రాష్ట్రం',
    businessType: 'వ్యాపార రకం',
    category: 'సామాజిక వర్గం',
    age: 'వయస్సు',
    income: 'వార్షిక ఆదాయం',
    notProvided: 'అందించబడలేదు',
    projectCost: 'అంచనా వేసిన ప్రాజెక్ట్ ఖర్చు',
    ownInvestment: 'స్వంత పెట్టుబడి',
    fundingGap: 'అంచనా వేసిన నిధుల అవసరం',
    readiness: 'దరఖాస్తు సంసిద్ధత',
    tracked: 'ట్రాక్ చేయబడుతున్న దరఖాస్తులు',
    none: 'ఇంకా ఏమీ లేవు',
    notRecorded: 'నమోదు కాలేదు',
    verifiedOn: 'ధృవీకరించబడింది',
    verificationUnavailable: 'ధృవీకరణ తేదీ అందుబాటులో లేదు — అధికారిక మార్గదర్శకాలను తనిఖీ చేయండి',
    disclaimers: [
      'ఈ నివేదిక కేవలం ప్రిపరేషన్ సహాయం మాత్రమే. ఇది దరఖాస్తు, ఆమోదం లేదా మంజూరు కాదు.',
      'నిధుల గణాంకాలు మీ స్వంత అంచనా అవసరం, ప్రభుత్వ హామీ మొత్తం కాదు.',
      'పథకం వివరాలు రికార్డ్ చేయబడిన అధికారిక వనరుల నుండి తీసుకోబడ్డాయి. అధికారిక పోర్టల్‌లో ఎల్లప్పుడూ ప్రస్తుత నిబంధనలను నిర్ధారించండి.',
      'సమాచారం తెలియదు అని చూపిన చోట, అది అందించబడలేదు లేదా ధృవీకరించబడలేదు అని అర్థం — ఇది తిరస్కరణ కాదు.',
    ],
  },
  kn: {
    title: 'ನನ್ನ ಬೆಂಬಲ ಮಾರ್ಗ',
    subtitle: 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಮತ್ತು ಪರಿಶೀಲಿಸಿದ ಯೋಜನೆ ದಾಖಲೆಗಳಿಂದ ಯೋಜನಾ ಸೇತು ರಚಿಸಿದೆ',
    printHint: 'ಇದನ್ನು PDF ಆಗಿ ಉಳಿಸಲು ನಿಮ್ಮ ಬ್ರೌಸರ್ ಮುದ್ರಣ ಆಯ್ಕೆಯನ್ನು ಬಳಸಿ.',
    stage: 'ಪ್ರಸ್ತುತ ವ್ಯವಹಾರ ಹಂತ',
    primaryNeed: 'ಪ್ರಾಥಮಿಕ ಬೆಂಬಲ ಅಗತ್ಯ',
    secondaryNeeds: 'ಇತರ ಬೆಂಬಲ ಅಗತ್ಯಗಳು',
    state: 'ರಾಜ್ಯ',
    businessType: 'ವ್ಯವಹಾರ ಪ್ರಕಾರ',
    category: 'ಸಾಮಾಜಿಕ ವರ್ಗ',
    age: 'ವಯಸ್ಸು',
    income: 'ವಾರ್ಷಿಕ ಆದಾಯ',
    notProvided: 'ಒದಗಿಸಲಾಗಿಲ್ಲ',
    projectCost: 'ಅಂದಾಜು ಯೋಜನಾ ವೆಚ್ಚ',
    ownInvestment: 'ಸ್ವಂತ ಹೂಡಿಕೆ',
    fundingGap: 'ಅಂದಾಜು ಹಣಕಾಸಿನ ಅಗತ್ಯ',
    readiness: 'ಅರ್ಜಿ ಸಿದ್ಧತೆ',
    tracked: 'ಟ್ರ್ಯಾಕ್ ಮಾಡಲಾಗುತ್ತಿರುವ ಅರ್ಜಿಗಳು',
    none: 'ಇನ್ನೂ ಯಾವುದೂ ಇಲ್ಲ',
    notRecorded: 'ದಾಖಲಾಗಿಲ್ಲ',
    verifiedOn: 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    verificationUnavailable: 'ಪರಿಶೀಲನೆ ದಿನಾಂಕ ಲಭ್ಯವಿಲ್ಲ — ಅಧಿಕೃತ ಮಾರ್ಗಸೂಚಿಗಳನ್ನು ಪರಿಶೀಲಿಸಿ',
    disclaimers: [
      'ಈ ವರದಿಯು ಕೇವಲ ಸಿದ್ಧತೆಯ ನೆರವು. ಇದು ಅರ್ಜಿ, ಅನುಮೋದನೆ ಅಥವಾ ಮಂಜೂರಾತಿ ಅಲ್ಲ.',
      'ಹಣಕಾಸಿನ ಅಂಕಿಅಂಶಗಳು ನಿಮ್ಮ ಸ್ವಂತ ಅಂದಾಜು ಅಗತ್ಯತೆಯಾಗಿದೆ, ಖಾತರಿಯ ಸರ್ಕಾರಿ ಮೊತ್ತವಲ್ಲ.',
      'ಯೋಜನೆಯ ವಿವರಗಳನ್ನು ಅಧಿಕೃತ ಮೂಲಗಳಿಂದ ಪಡೆಯಲಾಗಿದೆ. ಅಧಿಕೃತ ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ಪ್ರಸ್ತುತ ನಿಯಮಗಳನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ.',
      'ಮಾಹಿತಿ ಅಜ್ಞಾತ ಎಂದು ತೋರಿಸಿರುವಲ್ಲಿ, ಅದನ್ನು ಒದಗಿಸಲಾಗಿಲ್ಲ ಅಥವಾ ಪರಿಶೀಲಿಸಲಾಗಿಲ್ಲ ಎಂದರ್ಥ — ಇದು ತಿರಸ್ಕಾರವಲ್ಲ.',
    ],
  },
  ml: {
    title: 'എന്റെ സഹായ പാത',
    subtitle: 'നിങ്ങളുടെ പ്രൊഫൈലിൽ നിന്നും പരിശോധിച്ചുറപ്പിച്ച പദ്ധതി രേഖകളിൽ നിന്നും യോജന സേതു തയ്യാറാക്കിയത്',
    printHint: 'ഇത് PDF ആയി സേവ് ചെയ്യാൻ ബ്രൗസറിന്റെ പ്രിന്റ് ഓപ്ഷൻ ഉപയോഗിക്കുക.',
    stage: 'നിലവിലെ ബിസിനസ്സ് ഘട്ടം',
    primaryNeed: 'പ്രാഥമിക സഹായ ആവശ്യം',
    secondaryNeeds: 'മറ്റ് സഹായ ആവശ്യങ്ങൾ',
    state: 'സംസ്ഥാനം',
    businessType: 'ബിസിനസ്സ് തരം',
    category: 'സാമൂഹിക വിഭാഗം',
    age: 'പ്രായം',
    income: 'വാർഷിക വരുമാനം',
    notProvided: 'നൽകിയിട്ടില്ല',
    projectCost: 'കണക്കാക്കിയ പ്രോജക്റ്റ് ചെലവ്',
    ownInvestment: 'സ്വന്തം നിക്ഷേപം',
    fundingGap: 'കണക്കാക്കിയ ഫണ്ടിംഗ് ആവശ്യകത',
    readiness: 'അപേക്ഷാ സന്നദ്ധത',
    tracked: 'ട്രാക്ക് ചെയ്യുന്ന അപേക്ഷകൾ',
    none: 'ഇതുവരെ ഒന്നുമില്ല',
    notRecorded: 'രേഖപ്പെടുത്തിയിട്ടില്ല',
    verifiedOn: 'പരിശോധിച്ചുറപ്പിച്ചു',
    verificationUnavailable: 'പരിശോധനാ തീയതി ലഭ്യമല്ല — ഔദ്യോഗിക മാർഗ്ഗനിർദ്ദേശങ്ങൾ പരിശോധിക്കുക',
    disclaimers: [
      'ഈ റിപ്പോർട്ട് ഒരു തയ്യാറെടുപ്പ് സഹായം മാത്രമാണ്. ഇത് അപേക്ഷയോ അംഗീകാരമോ അനുമതിയോ അല്ല.',
      'ഫണ്ടിംഗ് കണക്കുകൾ നിങ്ങളുടെ സ്വന്തം കണക്കാക്കിയ ആവശ്യകതയാണ്, ഉറപ്പുനൽകിയ സർക്കാർ തുകയല്ല.',
      'പദ്ധതി വിശദാംശങ്ങൾ ഔദ്യോഗിക സ്രോതസ്സുകളിൽ നിന്ന് എടുത്തതാണ്. ഔദ്യോഗിക പോർട്ടലിൽ നിലവിലെ വ്യവസ്ഥകൾ സ്ഥിരീകരിക്കുക.',
      'വിവരം അജ്ഞാതമായി കാണിക്കുന്നിടത്ത്, അത് നൽകിയിട്ടില്ല അല്ലെങ്കിൽ പരിശോധിച്ചിട്ടില്ല എന്നാണ് അർത്ഥമാക്കുന്നത് — ഇത് നിരസിക്കലല്ല.',
    ],
  },
  mr: {
    title: 'माझा सहाय्य मार्ग',
    subtitle: 'योजना सेतूद्वारे तुमच्या प्रोफाइल आणि सत्यापित योजना नोंदींवरून तयार केलेले',
    printHint: 'हे PDF म्हणून जतन करण्यासाठी तुमच्या ब्राउझरचा प्रिंट पर्याय वापरा.',
    stage: 'सद्य व्यवसाय अवस्था',
    primaryNeed: 'प्राथमिक सहाय्य गरज',
    secondaryNeeds: 'इतर सहाय्य गरजा',
    state: 'राज्य',
    businessType: 'व्यवसाय प्रकार',
    category: 'सामाजिक प्रवर्ग',
    age: 'वय',
    income: 'वार्षिक उत्पन्न',
    notProvided: 'नमूद केलेले नाही',
    projectCost: 'अंदाजित प्रकल्प खर्च',
    ownInvestment: 'स्वतःची गुंतवणूक',
    fundingGap: 'अंदाजित निधी गरज',
    readiness: 'अर्ज तयारी',
    tracked: 'ट्रॅक केले जात असलेले अर्ज',
    none: 'अजून काहीही नाही',
    notRecorded: 'नोंदवलेले नाही',
    verifiedOn: 'सत्यापित',
    verificationUnavailable: 'सत्यापिती तारीख उपलब्ध नाही — अधिकृत मार्गदर्शक तत्त्वे तपासा',
    disclaimers: [
      'हा अहवाल केवळ तयारीसाठी सहाय्यक आहे. हा अर्ज, मान्यता किंवा मंजुरी नाही.',
      'निधीचे आकडे तुमची स्वतःची अंदाजित गरज आहे, शासनाची हमी दिलेली रक्कम नाही.',
      'योजनेची तपशील नोंदवलेल्या अधिकृत स्रोतांवरून घेतले आहेत. अधिकृत पोर्टलवर सध्याच्या अटी नेहमी खात्री करा.',
      'जिथे माहिती अज्ञात म्हणून दाखवली आहे, त्याचा अर्थ ती दिलेली नाही किंवा सत्यापित केलेली नाही — ही नकार नाही.',
    ],
  },
};

const MATCH_STATUS_COPY: Record<Language, {
  eligible: string;
  'near-match': string;
  'low-match': string;
}> = {
  en: {
    eligible: 'Matches your profile',
    'near-match': 'Close to qualifying',
    'low-match': 'Limited match',
  },
  hi: {
    eligible: 'आपकी प्रोफाइल से मेल',
    'near-match': 'योग्यता के निकट',
    'low-match': 'सीमित मेल',
  },
  ta: {
    eligible: 'உங்கள் சுயவிவரத்துடன் பொருந்துகிறது',
    'near-match': 'தகுதிக்கு அருகில்',
    'low-match': 'வரையறுக்கப்பட்ட பொருத்தம்',
  },
  te: {
    eligible: 'మీ ప్రొఫైల్‌కు సరిపోలుతుంది',
    'near-match': 'అర్హతకు దగ్గరగా',
    'low-match': 'పరిమిత సరిపోలిక',
  },
  kn: {
    eligible: 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್‌ಗೆ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ',
    'near-match': 'ಅರ್ಹತೆಗೆ ಹತ್ತಿರದಲ್ಲಿದೆ',
    'low-match': 'ಸೀಮಿತ ಹೊಂದಾಣಿಕೆ',
  },
  ml: {
    eligible: 'നിങ്ങളുടെ പ്രൊഫൈലുമായി പൊരുത്തപ്പെടുന്നു',
    'near-match': 'യോഗ്യതയ്ക്ക് അടുത്ത്',
    'low-match': 'പരിമിതമായ പൊരുത്തം',
  },
  mr: {
    eligible: 'तुमच्या प्रोफाइलशी जुळते',
    'near-match': 'पात्रतेच्या जवळ',
    'low-match': 'मर्यादित जुळणी',
  },
};

const PREP_STATE_COPY: Record<Language, {
  PREPARED: string;
  NOT_PREPARED: string;
  UNKNOWN: string;
  NOT_REQUIRED: string;
}> = {
  en: {
    PREPARED: 'Prepared',
    NOT_PREPARED: 'Not prepared',
    UNKNOWN: 'Unknown',
    NOT_REQUIRED: 'Not required',
  },
  hi: {
    PREPARED: 'तैयार',
    NOT_PREPARED: 'तैयार नहीं',
    UNKNOWN: 'अज्ञात',
    NOT_REQUIRED: 'आवश्यक नहीं',
  },
  ta: {
    PREPARED: 'தயாராக உள்ளது',
    NOT_PREPARED: 'தயாராக இல்லை',
    UNKNOWN: 'தெரியவில்லை',
    NOT_REQUIRED: 'தேவையில்லை',
  },
  te: {
    PREPARED: 'సిద్ధం',
    NOT_PREPARED: 'సిద్ధంగా లేదు',
    UNKNOWN: 'తెలియదు',
    NOT_REQUIRED: 'అవసరం లేదు',
  },
  kn: {
    PREPARED: 'ಸಿದ್ಧವಾಗಿದೆ',
    NOT_PREPARED: 'ಸಿದ್ಧವಾಗಿಲ್ಲ',
    UNKNOWN: 'ತಿಳಿದಿಲ್ಲ',
    NOT_REQUIRED: 'ಅಗತ್ಯವಿಲ್ಲ',
  },
  ml: {
    PREPARED: 'തയ്യാറാണ്',
    NOT_PREPARED: 'തയ്യാറല്ല',
    UNKNOWN: 'അജ്ഞാതം',
    NOT_REQUIRED: 'ആവശ്യമില്ല',
  },
  mr: {
    PREPARED: 'तयार',
    NOT_PREPARED: 'तयार नाही',
    UNKNOWN: 'अज्ञात',
    NOT_REQUIRED: 'आवश्यक नाही',
  },
};

const readable = (value?: string): string =>
  value ? value.replace(/_/g, ' ').toLowerCase() : '';

/** Builds the printable report. Pure function — same inputs, same output. */
export const buildPathwayReport = (args: {
  profile: UserProfile | null;
  pathway: SupportPathway;
  matchResults: MatchResult[];
  applications?: TrackedApplication[];
  lang?: Language;
  generatedAt?: string;
  today?: Date;
}): PathwayReport => {
  const lang: Language = args.lang && args.lang in COPY ? args.lang : 'en';
  const t = COPY[lang] || COPY.en;
  const { profile, pathway } = args;
  const generatedAt = args.generatedAt || new Date().toISOString();
  const today = args.today || new Date(generatedAt);

  const profileLines: ReportLine[] = [
    { label: t.state, value: profile?.state || t.notProvided },
    { label: t.businessType, value: profile?.businessType || t.notProvided },
    { label: t.category, value: profile?.category || t.notProvided },
    {
      label: t.age,
      value: profile?.age !== undefined && profile.age !== null ? String(profile.age) : t.notProvided,
    },
    {
      label: t.income,
      value:
        profile?.annualIncome !== undefined && profile.annualIncome !== null
          ? formatLakhCrore(profile.annualIncome, lang)
          : t.notProvided,
    },
    {
      label: t.primaryNeed,
      value: pathway.primaryNeed
        ? (SUPPORT_NEEDS_LOCALIZED[pathway.primaryNeed]?.[lang] || readable(String(pathway.primaryNeed)))
        : t.notProvided,
    },
    {
      label: t.secondaryNeeds,
      value:
        pathway.secondaryNeeds.length > 0
          ? pathway.secondaryNeeds
              .map((need) => SUPPORT_NEEDS_LOCALIZED[need]?.[lang] || readable(String(need)))
              .join(', ')
          : t.none,
    },
  ];

  const fundingLines: ReportLine[] = pathway.funding.hasFundingDetails
    ? [
        {
          label: t.projectCost,
          value: formatLakhCrore(pathway.funding.totalProjectCost, lang),
        },
        {
          label: t.ownInvestment,
          value: formatLakhCrore(pathway.funding.existingInvestment, lang),
        },
        { label: t.fundingGap, value: formatLakhCrore(pathway.funding.fundingGap, lang) },
      ]
    : [];

  const schemeIndex = new Map(args.matchResults.map((m) => [m.scheme.id, m]));

  const schemes: ReportSchemeEntry[] = [];
  pathway.supportStack.forEach((group) => {
    group.schemes.forEach((entry) => {
      const match = schemeIndex.get(entry.schemeId);
      const freshness = match ? evaluateSchemeFreshness(match.scheme, today) : null;
      const lastVerified = entry.provenance.lastVerified;

      const areaText = (group.area && SUPPORT_NEEDS_LOCALIZED[group.area]?.[lang])
        || resolveLocalizedPair(group.labelEn, group.labelHi, lang);

      schemes.push({
        schemeName: entry.schemeName,
        shortCode: entry.shortCode,
        areaLabel: areaText,
        matchPercentage: entry.matchPercentage,
        matchStatusLabel:
          MATCH_STATUS_COPY[lang]?.[entry.matchStatus as keyof typeof MATCH_STATUS_COPY['en']] ||
          MATCH_STATUS_COPY.en[entry.matchStatus as keyof typeof MATCH_STATUS_COPY['en']] ||
          readable(String(entry.matchStatus)),
        source: entry.provenance.source,
        sourceUrl: entry.provenance.sourceUrl,
        lastVerified,
        verificationLine: lastVerified
          ? `${t.verifiedOn} ${lastVerified}${
              freshness?.shouldRecheckOfficialSource
                ? ` — ${getLocalizedFreshness(freshness, lang).label}`
                : ''
            }`
          : t.verificationUnavailable,
      });
    });
  });

  const checklist: ReportChecklistItem[] = pathway.preparationChecklist.items.map((item) => ({
    label: resolveLocalizedPair(item.labelEn, item.labelHi, lang),
    stateLabel:
      PREP_STATE_COPY[lang]?.[item.state as keyof typeof PREP_STATE_COPY['en']] ||
      PREP_STATE_COPY.en[item.state as keyof typeof PREP_STATE_COPY['en']] ||
      readable(String(item.state)),
    isMandatory: Boolean(item.isMandatory),
  }));

  const trackedLines: ReportLine[] = (args.applications || []).map((application) => ({
    label: application.schemeName,
    value: application.appliedOn
      ? `${readable(application.status)} — ${application.appliedOn}`
      : readable(application.status) || t.notRecorded,
  }));

  const stageValue = (pathway.currentStage && LIFECYCLE_PHASES_LOCALIZED[pathway.currentStage]?.[lang])
    || resolveLocalizedPair(pathway.currentStageLabelEn, pathway.currentStageLabelHi, lang);

  const localizedAction = getLocalizedPathwayAction(pathway.nextBestAction, lang);
  const localizedReadiness = getLocalizedReadiness(pathway.readiness, lang);

  return {
    generatedAt,
    lang,
    title: t.title,
    subtitle: t.subtitle,
    printHint: t.printHint,
    profileLines,
    journeyLine: {
      label: t.stage,
      value: stageValue,
    },
    priorityLabels: pathway.recommendedSupportAreas
      .slice(0, 5)
      .map((area) => (SUPPORT_NEEDS_LOCALIZED[area.area]?.[lang] || resolveLocalizedPair(area.labelEn, area.labelHi, lang))),
    nextAction: {
      title: localizedAction.title,
      reason: localizedAction.reason,
      cta: localizedAction.cta,
    },
    readiness: {
      stateLabel: localizedReadiness.label,
      summary: localizedReadiness.summary,
      checks: pathway.readiness.checks.map((check) => {
        const { label, detail } = getLocalizedReadinessCheck(check, lang);
        return {
          label,
          value: detail,
        };
      }),
    },
    schemes,
    checklist,
    fundingLines,
    trackedLines,
    disclaimers: t.disclaimers,
  };
};
