/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const en = {
  // Navigation & Branding
  brandName: 'Yojana Setu',
  brandTagline: 'Intelligent Entrepreneur Command Center',
  navHome: 'Command Center',
  navSchemes: 'Schemes',
  navApplications: 'Applications',
  navDocuments: 'Documents',
  navProfile: 'Business Profile',

  // Greetings & Header
  greetingMorning: 'Good morning.',
  greetingAfternoon: 'Good afternoon.',
  greetingEvening: 'Good evening.',
  headerSubtitle: "Here's what matters for your business today.",
  headerSubtitleEmpty: "Here's where your business support journey stands.",

  // Next Best Action
  nextBestActionTitle: 'NEXT BEST ACTION',
  continueAction: 'Continue →',
  exploreAction: 'Explore →',

  // Business Journey
  businessJourneyTitle: 'YOUR BUSINESS JOURNEY',
  currentFocus: 'CURRENT FOCUS',
  relevantSchemes: 'relevant schemes',
  supportPathways: 'support pathways',
  applicationUnderway: 'application underway',
  applicationsUnderway: 'applications underway',
  exploreCategory: 'Explore',

  // Opportunities
  topOpportunitiesTitle: 'TOP OPPORTUNITIES',
  topOpportunityHeading: 'TOP OPPORTUNITY',
  matchScoreLabel: 'Match',
  actionNowBadge: 'ACTION NOW',
  highPriorityBadge: 'HIGH PRIORITY',
  reviewBadge: 'REVIEW',
  infoNeededBadge: 'INFORMATION NEEDED',
  lowPriorityBadge: 'LOW PRIORITY',
  whyThisSchemeTitle: 'WHY THIS SCHEME — AND WHY NOW?',
  eligibilityReviewed: 'Eligibility reviewed',
  financialFit: 'Financial fit',
  stateSupported: 'State supported',
  documentsPrepared: 'documents prepared',
  readyToReview: 'Ready to review',
  informationNeededText: 'Information needed',
  continueApplication: 'Continue Application',
  openOfficialPortal: 'Open Official Portal ↗',

  // Applications
  applicationsTitle: 'YOUR APPLICATIONS',
  readyToApply: 'Ready to Apply',
  preparing: 'Preparing',
  applied: 'Applied',
  approved: 'Approved',
  interested: 'Interested',
  viewApplications: 'View All Applications',
  noApplicationsYet: 'No active applications. Start by preparing your top opportunity.',

  // Documents
  documentCenterTitle: 'DOCUMENT CENTER',
  prepared: 'Prepared',
  needPreparation: 'Need Preparation',
  unknown: 'Unknown',
  notRequired: 'Not Required',
  reusableDocuments: 'Reusable Documents',
  applicationSpecificDocuments: 'Application-specific Documents',
  viewDocumentCenter: 'View Document Center',
  privacyGuarantee: 'Private & Secure: Yojana Setu never asks for identity numbers, passwords, or bank credentials, and sanitizes sensitive identifiers before persistence.',

  // Follow-ups
  followUpsTitle: 'UPCOMING FOLLOW-UPS',
  userReminderBadge: 'User reminder',
  officialDeadlineBadge: 'Official deadline',
  today: 'Today',
  noFollowUps: 'No upcoming follow-ups scheduled.',
  viewAllFollowUps: 'View All',
  addReminder: '+ Add Reminder',

  // Trust & Data Freshness
  trustTitle: 'TRUST & DATA FRESHNESS',
  recentlyVerified: 'Recently verified',
  officialSources: 'Official government portals',
  nodalSources: 'Statutory nodal agencies',
  needsVerification: 'Audit pending',
  verifiedOfficialBadge: 'Verified Official',
  knownNodalBadge: 'Known Nodal Platform',
  unverifiedBadge: 'External Source',
  statutoryAuditNotice: 'Audited against official gazettes & departmental notifications.',

  // Profile & Assessment
  profileCompleteness: 'Profile completeness',
  missingFieldsAlert: 'pieces of information are missing.',
  completeProfilePrompt: 'Completing your profile can improve recommendation accuracy.',
  completeProfileBtn: 'Complete Profile',
  editProfile: 'Edit Profile',

  // Empty & Fallback States
  welcomeTitle: 'WELCOME TO YOJANA SETU',
  welcomeSubtitle: 'Tell us about your business to unlock personalized scheme recommendations.',
  buildProfileBtn: 'Build My Business Profile',
  noMatchTitle: 'NO STRONG MATCHES YET',
  noMatchSubtitle: "We couldn't identify a high-confidence scheme from the information currently available.",
  reviewProfileBtn: 'Review Profile',
  exploreSupportBtn: 'Explore Support Areas',
  viewNearMatchesBtn: 'View Near Matches',

  // Modals & Actions
  close: 'Close',
  save: 'Save',
  saved: 'Saved',
  confirmSubmissionTitle: 'Confirm Official Portal Submission',
  confirmSubmissionNotice: 'Important: Opening an official portal does NOT automatically submit your application. You must complete the government procedure on their site.',
  confirmSubmissionQuestion: 'Did you complete and submit your application on the official portal?',
  confirmYes: 'Yes, I have submitted',
  confirmNo: 'Not yet, still preparing',
  portalAcknowledgedPrompt: 'Enter official acknowledgement number (optional):',

  // Dashboard 2.0 — Entrepreneur Command Center
  dashSubtitle: "Here's what needs your attention.",
  dashIndicatorReadiness: 'Profile readiness',
  dashIndicatorActions: 'Pending actions',
  dashIndicatorApplications: 'Active applications',
  dashIndicatorSaved: 'Saved schemes',
  dashContinueJourney: 'Continue where I left off',
  dashExploreMatches: 'Explore my matches',
  dashOpportunitiesTitle: 'TOP OPPORTUNITIES',
  dashWhyMatches: 'Why this matches',
  dashViewScheme: 'View Scheme →',
  dashPotentiallyRelevant: 'Potentially relevant',
  dashJourneyTitle: 'MY JOURNEY',
  dashCurrentStage: 'Current stage',
  dashStageDISCOVER: 'Discover',
  dashStageMATCH: 'Match',
  dashStageUNDERSTAND: 'Understand',
  dashStagePREPARE: 'Prepare',
  dashStageAPPLY: 'Apply',
  dashStageTRACK: 'Track',
  dashStageLineDISCOVER: 'Tell us about your business to discover relevant government support.',
  dashStageLineMATCH: 'Your profile has been matched against verified schemes.',
  dashStageLineUNDERSTAND: 'Review what each scheme offers and what it asks for.',
  dashStageLinePREPARE: 'Gather your documents and details before you apply.',
  dashStageLineAPPLY: 'Your applications are underway.',
  dashStageLineTRACK: 'Follow your submitted applications here.',
  dashCtaDISCOVER: 'Start with Scheme Matching',
  dashCtaMATCH: 'Review Your Matches',
  dashCtaUNDERSTAND: 'Explore Your Matches',
  dashCtaPREPARE: 'Continue Preparation',
  dashCtaAPPLY: 'View Applications',
  dashCtaTRACK: 'Track Applications',
  dashPrepTitle: 'PREPARATION CENTER',
  dashPrepDocuments: 'Documents',
  dashPrepFinancial: 'Financial profile',
  dashPrepRegistrations: 'Business registrations',
  dashPrepPortal: 'Official submission',
  dashPrepComplete: 'Complete',
  dashPrepAttention: 'Needs attention',
  dashPrepNotAssessed: 'Not yet assessed',
  dashPrepPortalAvailable: 'Official portal available',
  dashPrepOpenWorkspace: 'Open Preparation Workspace',
  dashStatMatches: 'MATCHES',
  dashStatMatchesDesc: 'Schemes matched to your profile',
  dashStatMatchesAction: 'View matches',
  dashStatApplications: 'APPLICATIONS',
  dashStatApplicationsDesc: 'In progress or submitted',
  dashStatApplicationsAction: 'View applications',
  dashStatSaved: 'SAVED',
  dashStatSavedDesc: 'Schemes you bookmarked',
  dashStatSavedAction: 'View saved',
  dashStatReadiness: 'READINESS',
  dashStatReadinessDesc: 'Profile completeness',
  dashStatReadinessAction: 'Complete profile',
  dashApplicationsTitle: 'APPLICATIONS',
  dashApplicationsEmpty: 'Applications you begin preparing will appear here.',
  dashViewApplications: 'View Applications',
  dashExploreYourMatches: 'Explore Your Matches',
  dashSavedTitle: 'SAVED SCHEMES',
  dashSchemesSaved: 'schemes saved',
  dashSavedEmpty: "You haven't saved any schemes yet.",
  dashViewAllSaved: 'View All Saved Schemes →',
  dashReadinessTitle: 'PROFILE READINESS',
  dashReadinessPersonal: 'Personal',
  dashReadinessBusiness: 'Business',
  dashReadinessFinancial: 'Financial',
  dashReadinessRegistrations: 'Registrations',
  dashReadinessDocuments: 'Documents',
  dashStateComplete: 'Complete',
  dashStateAttention: 'Needs attention',
  dashStateNotAssessed: 'Not yet assessed',
  dashCompleteProfile: 'Complete Profile →',
  dashTrustTitle: 'DATA & TRUST',
  dashTrustBasedOn: 'Recommendations are based on:',
  dashTrustProfile: 'Your profile',
  dashTrustDeterministic: 'Deterministic matching',
  dashTrustSource: 'Scheme source information',
  dashActivityTitle: 'RECENT ACTIVITY',
  dashReadinessIntro: 'A quick view of your profile across five areas.',
  dashViewProfile: 'View Profile',
  dashActivityEmpty: 'Your recent journey activity will appear here once you begin.',
  dashRemoveSaved: 'Remove from saved',
  dashTrustIntro: 'Trust signals for your top opportunities, checked against the scheme source.',
};
