/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const hi = {
  // Navigation & Branding
  brandName: 'योजना सेतु',
  brandTagline: 'उद्यमी निर्णय एवं एक्शन कमांड सेंटर',
  navHome: 'कमांड सेंटर',
  navSchemes: 'योजनाएं',
  navApplications: 'आवेदन',
  navDocuments: 'दस्तावेज',
  navProfile: 'व्यावसायिक प्रोफ़ाइल',

  // Greetings & Header
  greetingMorning: 'शुभ प्रभात।',
  greetingAfternoon: 'शुभ दोपहर।',
  greetingEvening: 'शुभ संध्या।',
  headerSubtitle: 'आज आपके व्यवसाय के लिए क्या महत्वपूर्ण है, यहां देखें।',
  headerSubtitleEmpty: 'यहां आपकी व्यवसाय सहायता यात्रा की स्थिति है।',

  // Next Best Action
  nextBestActionTitle: 'अगला सर्वोत्तम कदम',
  continueAction: 'आगे बढ़ें →',
  exploreAction: 'देखें →',

  // Business Journey
  businessJourneyTitle: 'आपकी व्यावसायिक यात्रा',
  currentFocus: 'वर्तमान फोकस',
  relevantSchemes: 'प्रासंगिक योजनाएं',
  supportPathways: 'सहायता मार्ग',
  applicationUnderway: 'आवेदन प्रक्रियाधीन',
  applicationsUnderway: 'आवेदन प्रक्रियाधीन',
  exploreCategory: 'देखें',

  // Opportunities
  topOpportunitiesTitle: 'शीर्ष अवसर',
  topOpportunityHeading: 'शीर्ष अवसर',
  matchScoreLabel: 'मैच',
  actionNowBadge: 'अभी कदम उठाएं',
  highPriorityBadge: 'उच्च प्राथमिकता',
  reviewBadge: 'समीक्षा करें',
  infoNeededBadge: 'जानकारी आवश्यक',
  lowPriorityBadge: 'सामान्य प्राथमिकता',
  whyThisSchemeTitle: 'यह योजना क्यों — और अभी क्यों?',
  eligibilityReviewed: 'पात्रता की समीक्षा की गई',
  financialFit: 'वित्तीय अनुकूलता',
  stateSupported: 'राज्य सरकार समर्थित',
  documentsPrepared: 'दस्तावेज तैयार',
  readyToReview: 'समीक्षा के लिए तैयार',
  informationNeededText: 'जानकारी की आवश्यकता है',
  continueApplication: 'आवेदन जारी रखें',
  openOfficialPortal: 'आधिकारिक पोर्टल खोलें ↗',

  // Applications
  applicationsTitle: 'आपके आवेदन',
  readyToApply: 'आवेदन के लिए तैयार',
  preparing: 'तैयारी चल रही है',
  applied: 'आवेदन किया गया',
  approved: 'स्वीकृत',
  interested: 'रुचि व्यक्त की',
  viewApplications: 'सभी आवेदन देखें',
  noApplicationsYet: 'कोई सक्रिय आवेदन नहीं। अपने शीर्ष अवसर की तैयारी से शुरू करें।',

  // Documents
  documentCenterTitle: 'दस्तावेज केंद्र',
  prepared: 'तैयार',
  needPreparation: 'तैयारी आवश्यक',
  unknown: 'अज्ञात',
  notRequired: 'आवश्यक नहीं',
  reusableDocuments: 'पुन: प्रयोज्य दस्तावेज',
  applicationSpecificDocuments: 'योजना-विशिष्ट दस्तावेज',
  viewDocumentCenter: 'दस्तावेज केंद्र देखें',
  privacyGuarantee: 'सुरक्षित एवं गोपनीय: योजना सेतु कभी भी पहचान संख्या, पासवर्ड या बैंक क्रेडेंशियल नहीं मांगता है, और संग्रहण से पूर्व संवेदनशील पहचानकर्ता स्वच्छ करता है।',

  // Follow-ups
  followUpsTitle: 'आगामी फॉलो-अप',
  userReminderBadge: 'उपयोगकर्ता अनुस्मारक',
  officialDeadlineBadge: 'सरकारी अंतिम तिथि',
  today: 'आज',
  noFollowUps: 'कोई आगामी फॉलो-अप निर्धारित नहीं है।',
  viewAllFollowUps: 'सभी देखें',
  addReminder: '+ अनुस्मारक जोड़ें',

  // Trust & Data Freshness
  trustTitle: 'विश्वसनीयता एवं डेटा नवीनता',
  recentlyVerified: 'हाल ही में सत्यापित',
  officialSources: 'आधिकारिक सरकारी पोर्टल',
  nodalSources: 'वैधानिक नोडल एजेंसियां',
  needsVerification: 'समीक्षा लंबित',
  verifiedOfficialBadge: 'सत्यापित आधिकारिक',
  knownNodalBadge: 'नोडल प्लेटफॉर्म',
  unverifiedBadge: 'बाहरी स्रोत',
  statutoryAuditNotice: 'आधिकारिक राजपत्रों और विभागीय अधिसूचनाओं के अनुसार ऑडिट किया गया।',

  // Profile & Assessment
  profileCompleteness: 'प्रोफ़ाइल पूर्णता',
  missingFieldsAlert: 'जानकारियां अधूरी हैं।',
  completeProfilePrompt: 'प्रोफ़ाइल पूरा करने से अनुशंसा सटीकता बेहतर होगी।',
  completeProfileBtn: 'प्रोफ़ाइल पूरा करें',
  editProfile: 'प्रोफ़ाइल संपादित करें',

  // Empty & Fallback States
  welcomeTitle: 'योजना सेतु में आपका स्वागत है',
  welcomeSubtitle: 'व्यक्तिगत योजना अनुशंसाओं को अनलॉक करने के लिए अपने व्यवसाय के बारे में बताएं।',
  buildProfileBtn: 'व्यावसायिक प्रोफ़ाइल बनाएं',
  noMatchTitle: 'अभी तक कोई मजबूत मैच नहीं मिला',
  noMatchSubtitle: 'वर्तमान जानकारी से हम किसी उच्च-विश्वास योजना की पहचान नहीं कर सके।',
  reviewProfileBtn: 'प्रोफ़ाइल की समीक्षा करें',
  exploreSupportBtn: 'सहायता क्षेत्र देखें',
  viewNearMatchesBtn: 'निकटतम मैच देखें',

  // Modals & Actions
  close: 'बंद करें',
  save: 'सहेजें',
  saved: 'सहेजा गया',
  confirmSubmissionTitle: 'आधिकारिक पोर्टल पर आवेदन जमा करने की पुष्टि',
  confirmSubmissionNotice: 'महत्वपूर्ण: आधिकारिक पोर्टल खोलने से आपका आवेदन स्वचालित रूप से जमा नहीं होता है। आपको उनकी वेबसाइट पर सरकारी प्रक्रिया पूरी करनी होगी।',
  confirmSubmissionQuestion: 'क्या आपने आधिकारिक पोर्टल पर अपना आवेदन पूरा करके जमा कर दिया है?',
  confirmYes: 'हाँ, मैंने जमा कर दिया है',
  confirmNo: 'अभी नहीं, अभी तैयारी जारी है',
  portalAcknowledgedPrompt: 'आधिकारिक पावती संख्या दर्ज करें (वैकल्पिक):',

  // Dashboard 2.0 — Entrepreneur Command Center
  dashSubtitle: 'आपके ध्यान देने योग्य बातें यहाँ हैं।',
  dashIndicatorReadiness: 'प्रोफ़ाइल तत्परता',
  dashIndicatorActions: 'लंबित कार्य',
  dashIndicatorApplications: 'सक्रिय आवेदन',
  dashIndicatorSaved: 'सहेजी गई योजनाएं',
  dashContinueJourney: 'जहाँ छोड़ा था वहाँ से जारी रखें',
  dashExploreMatches: 'मेरे मिलान देखें',
  dashOpportunitiesTitle: 'शीर्ष अवसर',
  dashWhyMatches: 'यह क्यों मेल खाता है',
  dashViewScheme: 'योजना देखें →',
  dashPotentiallyRelevant: 'संभावित रूप से प्रासंगिक',
  dashJourneyTitle: 'मेरी यात्रा',
  dashCurrentStage: 'वर्तमान चरण',
  dashStageDISCOVER: 'खोजें',
  dashStageMATCH: 'मिलान',
  dashStageUNDERSTAND: 'समझें',
  dashStagePREPARE: 'तैयारी',
  dashStageAPPLY: 'आवेदन',
  dashStageTRACK: 'ट्रैक करें',
  dashStageLineDISCOVER: 'प्रासंगिक सरकारी सहायता खोजने हेतु अपने व्यवसाय के बारे में बताएं।',
  dashStageLineMATCH: 'आपकी प्रोफ़ाइल का सत्यापित योजनाओं से मिलान किया गया है।',
  dashStageLineUNDERSTAND: 'प्रत्येक योजना क्या देती है और क्या मांगती है, इसकी समीक्षा करें।',
  dashStageLinePREPARE: 'आवेदन से पहले अपने दस्तावेज़ और विवरण जुटाएं।',
  dashStageLineAPPLY: 'आपके आवेदन प्रक्रियाधीन हैं।',
  dashStageLineTRACK: 'अपने प्रस्तुत आवेदनों का यहाँ अनुसरण करें।',
  dashCtaDISCOVER: 'योजना मिलान से शुरुआत करें',
  dashCtaMATCH: 'अपने मिलान देखें',
  dashCtaUNDERSTAND: 'अपने मिलान खोजें',
  dashCtaPREPARE: 'तैयारी जारी रखें',
  dashCtaAPPLY: 'आवेदन देखें',
  dashCtaTRACK: 'आवेदन ट्रैक करें',
  dashPrepTitle: 'तैयारी केंद्र',
  dashPrepDocuments: 'दस्तावेज़',
  dashPrepFinancial: 'वित्तीय प्रोफ़ाइल',
  dashPrepRegistrations: 'व्यवसाय पंजीकरण',
  dashPrepPortal: 'आधिकारिक प्रस्तुति',
  dashPrepComplete: 'पूर्ण',
  dashPrepAttention: 'ध्यान आवश्यक',
  dashPrepNotAssessed: 'अभी आकलन नहीं',
  dashPrepPortalAvailable: 'आधिकारिक पोर्टल उपलब्ध',
  dashPrepOpenWorkspace: 'तैयारी कार्यक्षेत्र खोलें',
  dashStatMatches: 'मैच',
  dashStatMatchesDesc: 'आपकी प्रोफ़ाइल से मेल खाने वाली योजनाएं',
  dashStatMatchesAction: 'मैच देखें',
  dashStatApplications: 'आवेदन',
  dashStatApplicationsDesc: 'प्रगति में या जमा किए गए',
  dashStatApplicationsAction: 'आवेदन देखें',
  dashStatSaved: 'सहेजे गए',
  dashStatSavedDesc: 'आप द्वारा बुकमार्क की गई योजनाएं',
  dashStatSavedAction: 'सहेजे गए देखें',
  dashStatReadiness: 'तैयारी',
  dashStatReadinessDesc: 'प्रोफ़ाइल पूर्णता',
  dashStatReadinessAction: 'प्रोफ़ाइल पूरी करें',
  dashApplicationsTitle: 'आवेदन',
  dashApplicationsEmpty: 'आपके द्वारा तैयार किए जाने वाले आवेदन यहाँ दिखेंगे।',
  dashViewApplications: 'आवेदन देखें',
  dashExploreYourMatches: 'अपने मिलान खोजें',
  dashSavedTitle: 'सहेजी गई योजनाएं',
  dashSchemesSaved: 'योजनाएं सहेजी गईं',
  dashSavedEmpty: 'आपने अभी कोई योजना नहीं सहेजी है।',
  dashViewAllSaved: 'सभी सहेजी गई योजनाएं देखें →',
  dashReadinessTitle: 'प्रोफ़ाइल तत्परता',
  dashReadinessPersonal: 'व्यक्तिगत',
  dashReadinessBusiness: 'व्यावसायिक',
  dashReadinessFinancial: 'वित्तीय',
  dashReadinessRegistrations: 'पंजीकरण',
  dashReadinessDocuments: 'दस्तावेज़',
  dashStateComplete: 'पूर्ण',
  dashStateAttention: 'ध्यान आवश्यक',
  dashStateNotAssessed: 'अभी आकलन नहीं',
  dashCompleteProfile: 'प्रोफ़ाइल पूर्ण करें →',
  dashTrustTitle: 'डेटा एवं विश्वास',
  dashTrustBasedOn: 'अनुशंसाएं इन पर आधारित हैं:',
  dashTrustProfile: 'आपकी प्रोफ़ाइल',
  dashTrustDeterministic: 'नियतात्मक मिलान',
  dashTrustSource: 'योजना स्रोत जानकारी',
  dashActivityTitle: 'हाल की गतिविधि',
  dashReadinessIntro: 'पांचों क्षेत्रों में आपकी प्रोफ़ाइल की एक त्वरित झलक।',
  dashViewProfile: 'प्रोफ़ाइल देखें',
  dashActivityEmpty: 'आपके शुरू करते ही आपकी हाल की गतिविधि यहां दिखाई देगी।',
  dashRemoveSaved: 'सहेजे गए से हटाएं',
  dashTrustIntro: 'आपके शीर्ष अवसरों के लिए विश्वास संकेत, योजना स्रोत से सत्यापित।',
};
