/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const kn = {
  // Navigation & Branding
  brandName: 'ಯೋಜನಾ ಸೇತು',
  brandTagline: 'ಬುದ್ಧಿವಂತ ಉದ್ಯಮಿ ಕಮಾಂಡ್ ಸೆಂಟರ್',
  navHome: 'ಕಮಾಂಡ್ ಸೆಂಟರ್',
  navSchemes: 'ಯೋಜನೆಗಳು',
  navApplications: 'ಅರ್ಜಿಗಳು',
  navDocuments: 'ದಾಖಲೆಗಳು',
  navProfile: 'ವ್ಯಾಪಾರ ಪ್ರೊಫೈಲ್',

  // Greetings & Header
  greetingMorning: 'ಶುಭೋದಯ.',
  greetingAfternoon: 'ಶುಭ ಮಧ್ಯಾಹ್ನ.',
  greetingEvening: 'ಶುಭ ಸಂಜೆ.',
  headerSubtitle: 'ಇಂದು ನಿಮ್ಮ ವ್ಯಾಪಾರಕ್ಕೆ ಮುಖ್ಯವಾದ ಮಾಹಿತಿ ಇಲ್ಲಿದೆ.',
  headerSubtitleEmpty: 'ನಿಮ್ಮ ವ್ಯಾಪಾರ ಬೆಂಬಲ ಪ್ರಯಾಣದ ಪ್ರಸ್ತುತ ಸ್ಥಿತಿ ಇಲ್ಲಿದೆ.',

  // Next Best Action
  nextBestActionTitle: 'ಮುಂದಿನ ಅತ್ಯುತ್ತಮ ಕ್ರಮ',
  continueAction: 'ಮುಂದುವರಿಯಿರಿ →',
  exploreAction: 'ಅನ್ವೇಷಿಸಿ →',

  // Business Journey
  businessJourneyTitle: 'ನಿಮ್ಮ ವ್ಯಾಪಾರ ಪ್ರಯಾಣ',
  currentFocus: 'ಪ್ರಸ್ತುತ ಗಮನ',
  relevantSchemes: 'ಸಂಬಂಧಿತ ಯೋಜನೆಗಳು',
  supportPathways: 'ಬೆಂಬಲ ಮಾರ್ಗಗಳು',
  applicationUnderway: 'ಅರ್ಜಿ ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿದೆ',
  applicationsUnderway: 'ಅರ್ಜಿಗಳು ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿವೆ',
  exploreCategory: 'ಅನ್ವೇಷಿಸಿ',

  // Opportunities
  topOpportunitiesTitle: 'ಉನ್ನತ ಅವಕಾಶಗಳು',
  topOpportunityHeading: 'ಉನ್ನತ ಅವಕಾಶ',
  matchScoreLabel: 'ಹೊಂದಾಣಿಕೆ',
  actionNowBadge: 'ತಕ್ಷಣದ ಕ್ರಮ',
  highPriorityBadge: 'ಹೆಚ್ಚಿನ ಆದ್ಯತೆ',
  reviewBadge: 'ಪರಿಶೀಲಿಸಿ',
  infoNeededBadge: 'ಮಾಹಿತಿ ಅಗತ್ಯವಿದೆ',
  lowPriorityBadge: 'ಕಡಿಮೆ ಆದ್ಯತೆ',
  whyThisSchemeTitle: 'ಈ ಯೋಜನೆ ಏಕೆ — ಮತ್ತು ಈಗಲೇ ಏಕೆ?',
  eligibilityReviewed: 'ಅರ್ಹತೆ ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
  financialFit: 'ಹಣಕಾಸು ಹೊಂದಾಣಿಕೆ',
  stateSupported: 'ರಾಜ್ಯ ಸರ್ಕಾರದ ಬೆಂಬಲ',
  documentsPrepared: 'ದಾಖಲೆಗಳು ಸಿದ್ಧವಾಗಿವೆ',
  readyToReview: 'ಪರಿಶೀಲನೆಗೆ ಸಿದ್ಧವಾಗಿದೆ',
  informationNeededText: 'ಮಾಹಿತಿ ಅಗತ್ಯವಿದೆ',
  continueApplication: 'ಅರ್ಜಿಯನ್ನು ಮುಂದುವರಿಸಿ →',
  openOfficialPortal: 'ಅಧಿಕೃತ ಪೋರ್ಟಲ್ ತೆರೆಯಿರಿ ↗',

  // Applications
  applicationsTitle: 'ನಿಮ್ಮ ಅರ್ಜಿಗಳು',
  readyToApply: 'ಅರ್ಜಿ ಸಲ್ಲಿಸಲು ಸಿದ್ಧ',
  preparing: 'ಸಿದ್ಧವಾಗುತ್ತಿದೆ',
  applied: 'ಅರ್ಜಿ ಸಲ್ಲಿಸಲಾಗಿದೆ',
  approved: 'ಅನುಮೋದಿಸಲಾಗಿದೆ',
  interested: 'ಆಸಕ್ತಿ ವ್ಯಕ್ತಪಡಿಸಲಾಗಿದೆ',
  viewApplications: 'ಎಲ್ಲಾ ಅರ್ಜಿಗಳನ್ನು ವೀಕ್ಷಿಸಿ →',
  noApplicationsYet: 'ಯಾವುದೇ ಸಕ್ರಿಯ ಅರ್ಜಿಗಳಿಲ್ಲ. ನಿಮ್ಮ ಉನ್ನತ ಅವಕಾಶವನ್ನು ಸಿದ್ಧಪಡಿಸುವ ಮೂಲಕ ಪ್ರಾರಂಭಿಸಿ.',

  // Documents
  documentCenterTitle: 'ದಾಖಲೆ ಕೇಂದ್ರ',
  prepared: 'ಸಿದ್ಧವಾಗಿದೆ',
  needPreparation: 'ಸಿದ್ಧತೆ ಅಗತ್ಯವಿದೆ',
  unknown: 'ತಿಳಿದಿಲ್ಲ',
  notRequired: 'ಅಗತ್ಯವಿಲ್ಲ',
  reusableDocuments: 'ಮರುಬಳಕೆ ಮಾಡಬಹುದಾದ ದಾಖಲೆಗಳು',
  applicationSpecificDocuments: 'ಯೋಜನೆ-ನಿರ್ದಿಷ್ಟ ದಾಖಲೆಗಳು',
  viewDocumentCenter: 'ದಾಖಲೆ ಕೇಂದ್ರವನ್ನು ವೀಕ್ಷಿಸಿ →',
  privacyGuarantee: 'ಸುರಕ್ಷಿತ ಮತ್ತು ಗೌಪ್ಯ: ಯೋಜನಾ ಸೇತು ಗುರುತಿನ ಸಂಖ್ಯೆಗಳು, ಪಾಸ್‌ವರ್ಡ್‌ಗಳು ಅಥವಾ ಬ್ಯಾಂಕ್ ವಿವರಗಳನ್ನು ಎಂದಿಗೂ ಕೇಳುವುದಿಲ್ಲ; ಸಂಗ್ರಹಣೆಗೆ ಮೊದಲು ಸೂಕ್ಷ್ಮ ಗುರುತುಗಳನ್ನು ಸ್ವಚ್ಛಗೊಳಿಸಲಾಗುತ್ತದೆ.',

  // Follow-ups
  followUpsTitle: 'ಮುಂಬರುವ ಜ್ಞಾಪನೆಗಳು',
  userReminderBadge: 'ಬಳಕೆದಾರ ಜ್ಞಾಪನೆ',
  officialDeadlineBadge: 'ಅಧಿಕೃತ ಗಡುವು',
  today: 'ಇಂದು',
  noFollowUps: 'ಯಾವುದೇ ಮುಂಬರುವ ಜ್ಞಾಪನೆಗಳಿಲ್ಲ.',
  viewAllFollowUps: 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ →',
  addReminder: '+ ಜ್ಞಾಪನೆ ಸೇರಿಸಿ',

  // Trust & Data Freshness
  trustTitle: 'ವಿಶ್ವಾಸಾರ್ಹತೆ ಮತ್ತು ಡೇಟಾ ನವೀಕರಣ',
  recentlyVerified: 'ಇತ್ತೀಚೆಗೆ ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
  officialSources: 'ಅಧಿಕೃತ ಸರ್ಕಾರಿ ಪೋರ್ಟಲ್‌ಗಳು',
  nodalSources: 'ಶಾಸನಬದ್ಧ ನೋಡಲ್ ಏಜೆನ್ಸಿಗಳು',
  needsVerification: 'ಪರಿಶೀಲನೆ ಬಾಕಿ ಇದೆ',
  verifiedOfficialBadge: 'ಪರಿಶೀಲಿಸಿದ ಅಧಿಕೃತ ತಾಣ',
  knownNodalBadge: 'ಮಾನ್ಯತೆ ಪಡೆದ ನೋಡಲ್ ವೇದಿಕೆ',
  unverifiedBadge: 'ಬಾಹ್ಯ ಮೂಲ',
  statutoryAuditNotice: 'ಸರ್ಕಾರಿ ಗೆಜೆಟ್‌ಗಳು ಮತ್ತು ಇಲಾಖಾ ಅಧಿಸೂಚನೆಗಳ ಪ್ರಕಾರ ಪರಿಶೀಲಿಸಲಾಗಿದೆ.',

  // Profile & Assessment
  profileCompleteness: 'ಪ್ರೊಫೈಲ್ ಪೂರ್ಣತೆ',
  missingFieldsAlert: 'ಮಾಹಿತಿ ಅಪೂರ್ಣವಾಗಿದೆ.',
  completeProfilePrompt: 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಪೂರ್ಣಗೊಳಿಸುವುದರಿಂದ ಶಿಫಾರಸುಗಳ ನಿಖರತೆ ಸುಧಾರಿಸುತ್ತದೆ.',
  completeProfileBtn: 'ಪ್ರೊಫೈಲ್ ಪೂರ್ಣಗೊಳಿಸಿ →',
  editProfile: 'ಪ್ರೊಫೈಲ್ ತಿದ್ದಿ',

  // Empty & Fallback States
  welcomeTitle: 'ಯೋಜನಾ ಸೇತುಗೆ ಸುಸ್ವಾಗತ',
  welcomeSubtitle: 'ವೈಯಕ್ತಿಕಗೊಳಿಸಿದ ಯೋಜನೆ ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಲು ನಿಮ್ಮ ವ್ಯಾಪಾರದ ಬಗ್ಗೆ ನಮಗೆ ತಿಳಿಸಿ.',
  buildProfileBtn: 'ವ್ಯಾಪಾರ ಪ್ರೊಫೈಲ್ ರಚಿಸಿ →',
  noMatchTitle: 'ಇನ್ನೂ ಬಲವಾದ ಹೊಂದಾಣಿಕೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
  noMatchSubtitle: 'ಪ್ರಸ್ತುತ ಮಾಹಿತಿಯ ಆಧಾರದ ಮೇಲೆ ಯಾವುದೇ ಹೆಚ್ಚಿನ ಹೊಂದಾಣಿಕೆಯ ಯೋಜನೆಯನ್ನು ಗುರುತಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.',
  reviewProfileBtn: 'ಪ್ರೊಫೈಲ್ ಪರಿಶೀಲಿಸಿ',
  exploreSupportBtn: 'ಬೆಂಬಲ ಕ್ಷೇತ್ರಗಳನ್ನು ಅನ್ವೇಷಿಸಿ',
  viewNearMatchesBtn: 'ಹತ್ತಿರದ ಹೊಂದಾಣಿಕೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ',

  // Modals & Actions
  close: 'ಮುಚ್ಚಿ',
  save: 'ಉಳಿಸಿ',
  saved: 'ಉಳಿಸಲಾಗಿದೆ',
  confirmSubmissionTitle: 'ಅಧಿಕೃತ ಪೋರ್ಟಲ್ ಸಲ್ಲಿಕೆಯನ್ನು ದೃಢೀಕರಿಸಿ',
  confirmSubmissionNotice: 'ಪ್ರಮುಖ ಸೂಚನೆ: ಅಧಿಕೃತ ಪೋರ್ಟಲ್ ತೆರೆಯುವುದರಿಂದ ನಿಮ್ಮ ಅರ್ಜಿ ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಸಲ್ಲಿಕೆಯಾಗುವುದಿಲ್ಲ. ನೀವು ಅವರ ವೆಬ್‌ಸೈಟ್‌ನಲ್ಲಿ ಸರ್ಕಾರಿ ಪ್ರಕ್ರಿಯೆಯನ್ನು ಪೂರ್ಣಗೊಳಿಸಬೇಕು.',
  confirmSubmissionQuestion: 'ನೀವು ಅಧಿಕೃತ ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ನಿಮ್ಮ ಅರ್ಜಿಯನ್ನು ಪೂರ್ಣಗೊಳಿಸಿ ಸಲ್ಲಿಸಿದ್ದೀರಾ?',
  confirmYes: 'ಹೌದು, ನಾನು ಸಲ್ಲಿಸಿದ್ದೇನೆ',
  confirmNo: 'ಇನ್ನೂ ಇಲ್ಲ, ಸಿದ್ಧತೆ ನಡೆಯುತ್ತಿದೆ',
  portalAcknowledgedPrompt: 'ಅಧಿಕೃತ ಸ್ವೀಕೃತಿ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ (ಐಚ್ಛಿಕ):',

  // Dashboard 2.0 — Entrepreneur Command Center
  dashSubtitle: 'ನಿಮ್ಮ ಗಮನ ಅಗತ್ಯವಿರುವುದು ಇಲ್ಲಿದೆ.',
  dashIndicatorReadiness: 'ಪ್ರೊಫೈಲ್ ಸನ್ನದ್ಧತೆ',
  dashIndicatorActions: 'ಬಾಕಿ ಕಾರ್ಯಗಳು',
  dashIndicatorApplications: 'ಸಕ್ರಿಯ ಅರ್ಜಿಗಳು',
  dashIndicatorSaved: 'ಉಳಿಸಿದ ಯೋಜನೆಗಳು',
  dashContinueJourney: 'ನಿಲ್ಲಿಸಿದಲ್ಲಿಂದ ಮುಂದುವರಿಸಿ →',
  dashExploreMatches: 'ನನ್ನ ಹೊಂದಾಣಿಕೆಗಳನ್ನು ನೋಡಿ →',
  dashOpportunitiesTitle: 'ಪ್ರಮುಖ ಅವಕಾಶಗಳು',
  dashWhyMatches: 'ಇದು ಏಕೆ ಹೊಂದಾಣಿಕೆಯಾಗುತ್ತದೆ',
  dashViewScheme: 'ಯೋಜನೆ ವೀಕ್ಷಿಸಿ →',
  dashPotentiallyRelevant: 'ಸಂಬಂಧಿತವಾಗಿರಬಹುದು',
  dashJourneyTitle: 'ನನ್ನ ಪಯಣ',
  dashCurrentStage: 'ಪ್ರಸ್ತುತ ಹಂತ',
  dashStageDISCOVER: 'ಅನ್ವೇಷಿಸಿ',
  dashStageMATCH: 'ಹೊಂದಿಸಿ',
  dashStageUNDERSTAND: 'ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ',
  dashStagePREPARE: 'ಸಿದ್ಧಪಡಿಸಿ',
  dashStageAPPLY: 'ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
  dashStageTRACK: 'ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
  dashStageLineDISCOVER: 'ಸಂಬಂಧಿತ ಸರ್ಕಾರಿ ಬೆಂಬಲವನ್ನು ಕಂಡುಹಿಡಿಯಲು ನಿಮ್ಮ ವ್ಯವಹಾರದ ಬಗ್ಗೆ ತಿಳಿಸಿ.',
  dashStageLineMATCH: 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಅನ್ನು ಪರಿಶೀಲಿಸಿದ ಯೋಜನೆಗಳೊಂದಿಗೆ ಹೊಂದಿಸಲಾಗಿದೆ.',
  dashStageLineUNDERSTAND: 'ಪ್ರತಿ ಯೋಜನೆ ಏನು ನೀಡುತ್ತದೆ ಮತ್ತು ಏನು ಕೇಳುತ್ತದೆ ಎಂಬುದನ್ನು ಪರಿಶೀಲಿಸಿ.',
  dashStageLinePREPARE: 'ಅರ್ಜಿ ಸಲ್ಲಿಸುವ ಮೊದಲು ನಿಮ್ಮ ದಾಖಲೆಗಳು ಮತ್ತು ವಿವರಗಳನ್ನು ಸಂಗ್ರಹಿಸಿ.',
  dashStageLineAPPLY: 'ನಿಮ್ಮ ಅರ್ಜಿಗಳು ಪ್ರಗತಿಯಲ್ಲಿವೆ.',
  dashStageLineTRACK: 'ಸಲ್ಲಿಸಿದ ಅರ್ಜಿಗಳನ್ನು ಇಲ್ಲಿ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ.',
  dashCtaDISCOVER: 'ಯೋಜನೆ ಹೊಂದಾಣಿಕೆಯೊಂದಿಗೆ ಪ್ರಾರಂಭಿಸಿ →',
  dashCtaMATCH: 'ನಿಮ್ಮ ಹೊಂದಾಣಿಕೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ →',
  dashCtaUNDERSTAND: 'ನಿಮ್ಮ ಹೊಂದಾಣಿಕೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ →',
  dashCtaPREPARE: 'ಸಿದ್ಧತೆಯನ್ನು ಮುಂದುವರಿಸಿ →',
  dashCtaAPPLY: 'ಅರ್ಜಿಗಳನ್ನು ವೀಕ್ಷಿಸಿ →',
  dashCtaTRACK: 'ಅರ್ಜಿಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ →',
  dashPrepTitle: 'ಸಿದ್ಧತಾ ಕೇಂದ್ರ',
  dashPrepDocuments: 'ದಾಖಲೆಗಳು',
  dashPrepFinancial: 'ಹಣಕಾಸು ಪ್ರೊಫೈಲ್',
  dashPrepRegistrations: 'ವ್ಯವಹಾರ ನೋಂದಣಿಗಳು',
  dashPrepPortal: 'ಅಧಿಕೃತ ಸಲ್ಲಿಕೆ',
  dashPrepComplete: 'ಪೂರ್ಣ',
  dashPrepAttention: 'ಗಮನ ಅಗತ್ಯ',
  dashPrepNotAssessed: 'ಇನ್ನೂ ಮೌಲ್ಯಮಾಪನವಾಗಿಲ್ಲ',
  dashPrepPortalAvailable: 'ಅಧಿಕೃತ ಪೋರ್ಟಲ್ ಲಭ್ಯವಿದೆ',
  dashPrepOpenWorkspace: 'ಸಿದ್ಧತಾ ಕಾರ್ಯಕ್ಷೇತ್ರ ತೆರೆಯಿರಿ →',
  dashApplicationsTitle: 'ಅರ್ಜಿಗಳು',
  dashApplicationsEmpty: 'ನೀವು ಸಿದ್ಧಪಡಿಸಲು ಪ್ರಾರಂಭಿಸುವ ಅರ್ಜಿಗಳು ಇಲ್ಲಿ ಕಾಣಿಸಿಕೊಳ್ಳುತ್ತವೆ.',
  dashViewApplications: 'ಅರ್ಜಿಗಳನ್ನು ವೀಕ್ಷಿಸಿ →',
  dashExploreYourMatches: 'ನಿಮ್ಮ ಹೊಂದಾಣಿಕೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ →',
  dashSavedTitle: 'ಉಳಿಸಿದ ಯೋಜನೆಗಳು',
  dashSchemesSaved: 'ಯೋಜನೆಗಳನ್ನು ಉಳಿಸಲಾಗಿದೆ',
  dashSavedEmpty: 'ನೀವು ಇನ್ನೂ ಯಾವುದೇ ಯೋಜನೆಯನ್ನು ಉಳಿಸಿಲ್ಲ.',
  dashViewAllSaved: 'ಉಳಿಸಿದ ಎಲ್ಲಾ ಯೋಜನೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ →',
  dashReadinessTitle: 'ಪ್ರೊಫೈಲ್ ಸನ್ನದ್ಧತೆ',
  dashReadinessPersonal: 'ವೈಯಕ್ತಿಕ',
  dashReadinessBusiness: 'ವ್ಯವಹಾರ',
  dashReadinessFinancial: 'ಹಣಕಾಸು',
  dashReadinessRegistrations: 'ನೋಂದಣಿಗಳು',
  dashReadinessDocuments: 'ದಾಖಲೆಗಳು',
  dashStateComplete: 'ಪೂರ್ಣ',
  dashStateAttention: 'ಗಮನ ಅಗತ್ಯ',
  dashStateNotAssessed: 'ಇನ್ನೂ ಮೌಲ್ಯಮಾಪನವಾಗಿಲ್ಲ',
  dashCompleteProfile: 'ಪ್ರೊಫೈಲ್ ಪೂರ್ಣಗೊಳಿಸಿ →',
  dashTrustTitle: 'ಡೇಟಾ ಮತ್ತು ನಂಬಿಕೆ',
  dashTrustBasedOn: 'ಶಿಫಾರಸುಗಳು ಇವನ್ನು ಆಧರಿಸಿವೆ:',
  dashTrustProfile: 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್',
  dashTrustDeterministic: 'ನಿರ್ಣಾಯಕ ಹೊಂದಾಣಿಕೆ',
  dashTrustSource: 'ಯೋಜನೆಯ ಮೂಲ ಮಾಹಿತಿ',
  dashActivityTitle: 'ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ',
  dashReadinessIntro: 'ಐದು ಕ್ಷೇತ್ರಗಳಲ್ಲಿ ನಿಮ್ಮ ಪ್ರೊಫೈಲ್‌ನ ತ್ವರಿತ ನೋಟ.',
  dashViewProfile: 'ಪ್ರೊಫೈಲ್ ವೀಕ್ಷಿಸಿ →',
  dashActivityEmpty: 'ನೀವು ಪ್ರಾರಂಭಿಸಿದ ತಕ್ಷಣ ನಿಮ್ಮ ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತದೆ.',
  dashRemoveSaved: 'ಉಳಿಸಿದವುಗಳಿಂದ ತೆಗೆದುಹಾಕಿ',
  dashTrustIntro: 'ನಿಮ್ಮ ಪ್ರಮುಖ ಅವಕಾಶಗಳಿಗಾಗಿ ವಿಶ್ವಾಸ ಸಂಕೇತಗಳು, ಯೋಜನೆಯ ಮೂಲದಿಂದ ಪರಿಶೀಲಿಸಲಾಗಿದೆ.',
};
