/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const ml = {
  // Navigation & Branding
  brandName: 'യോജനാ സേതു',
  brandTagline: 'ഇന്റലിജന്റ് സംരംഭക കമാൻഡ് സെന്റർ',
  navHome: 'കമാൻഡ് സെന്റർ',
  navSchemes: 'പദ്ധതികൾ',
  navApplications: 'അപേക്ഷകൾ',
  navDocuments: 'രേഖകൾ',
  navProfile: 'ബിസിനസ് പ്രൊഫൈൽ',

  // Greetings & Header
  greetingMorning: 'സുപ്രഭാതം.',
  greetingAfternoon: 'ശുഭ ഉച്ചതിരിഞ്ഞ്.',
  greetingEvening: 'ശുഭ സായാഹ്നം.',
  headerSubtitle: 'ഇന്ന് നിങ്ങളുടെ ബിസിനസ്സിന് ആവശ്യമായ പ്രധാന വിവരങ്ങൾ ഇവിടെയുണ്ട്.',
  headerSubtitleEmpty: 'നിങ്ങളുടെ ബിസിനസ്സ് പിന്തുണാ യാത്രയുടെ നിലവിലെ അവസ്ഥ ഇവിടെ കാണാം.',

  // Next Best Action
  nextBestActionTitle: 'അടുത്ത മികച്ച നടപടി',
  continueAction: 'തുടരുക →',
  exploreAction: 'പരിശോധിക്കുക →',

  // Business Journey
  businessJourneyTitle: 'നിങ്ങളുടെ ബിസിനസ്സ് യാത്ര',
  currentFocus: 'നിലവിലെ ശ്രദ്ധ',
  relevantSchemes: 'അനുയോജ്യമായ പദ്ധതികൾ',
  supportPathways: 'പിന്തുണാ വഴികൾ',
  applicationUnderway: 'അപേക്ഷ പ്രക്രിയയിലാണ്',
  applicationsUnderway: 'അപേക്ഷകൾ പ്രക്രിയയിലാണ്',
  exploreCategory: 'പരിശോധിക്കുക',

  // Opportunities
  topOpportunitiesTitle: 'പ്രധാന അവസരങ്ങൾ',
  topOpportunityHeading: 'പ്രധാന അവസരം',
  matchScoreLabel: 'പൊരുത്തം',
  actionNowBadge: 'ഉടൻ നടപടി സ്വീകരിക്കുക',
  highPriorityBadge: 'ഉയർന്ന മുൻഗണന',
  reviewBadge: 'പരിശോധിക്കുക',
  infoNeededBadge: 'വിവരങ്ങൾ ആവശ്യമാണ്',
  lowPriorityBadge: 'കുറഞ്ഞ മുൻഗണന',
  whyThisSchemeTitle: 'എന്തുകൊണ്ട് ഈ പദ്ധതി — എന്തുകൊണ്ട് ഇപ്പോൾ?',
  eligibilityReviewed: 'യോഗ്യത പരിശോധിച്ചു',
  financialFit: 'സാമ്പത്തിക പൊരുത്തം',
  stateSupported: 'സംസ്ഥാന സർക്കാർ പിന്തുണ',
  documentsPrepared: 'രേഖകൾ സജ്ജമാണ്',
  readyToReview: 'പരിശോധനയ്ക്ക് സജ്ജം',
  informationNeededText: 'വിവരങ്ങൾ ആവശ്യമാണ്',
  continueApplication: 'അപേക്ഷ തുടരുക',
  openOfficialPortal: 'ഔദ്യോഗിക പോർട്ടൽ തുറക്കുക ↗',

  // Applications
  applicationsTitle: 'നിങ്ങളുടെ അപേക്ഷകൾ',
  readyToApply: 'അപേക്ഷിക്കാൻ തയ്യാറാണ്',
  preparing: 'തയ്യാറാകുന്നു',
  applied: 'അപേക്ഷ സമർപ്പിച്ചു',
  approved: 'അംഗീകരിച്ചു',
  interested: 'താൽപ്പര്യം പ്രകടിപ്പിച്ചു',
  viewApplications: 'എല്ലാ അപേക്ഷകളും കാണുക',
  noApplicationsYet: 'സജീവമായ അപേക്ഷകളൊന്നുമില്ല. നിങ്ങളുടെ പ്രധാന അവസരം തയ്യാറാക്കി ആരംഭിക്കുക.',

  // Documents
  documentCenterTitle: 'ഡോക്യുമെന്റ് സെന്റർ',
  prepared: 'സജ്ജമാണ്',
  needPreparation: 'തയ്യാറാക്കൽ ആവശ്യമാണ്',
  unknown: 'അറിയില്ല',
  notRequired: 'ആവശ്യമില്ല',
  reusableDocuments: 'പുനരുപയോഗിക്കാവുന്ന രേഖകൾ',
  applicationSpecificDocuments: 'പദ്ധതി നിർദ്ദിഷ്ട രേഖകൾ',
  viewDocumentCenter: 'രേഖകളുടെ കേന്ദ്രം കാണുക',
  privacyGuarantee: 'സുരക്ഷിതവും രഹസ്യാത്മകവും: യോജനാ സേതു തിരിച്ചറിയൽ നമ്പറുകളോ പാസ്‌വേഡുകളോ ബാങ്ക് വിവരങ്ങളോ ഒരിക്കലും ചോദിക്കില്ല; സംഭരണത്തിന് മുമ്പ് സെൻസിറ്റീവ് തിരിച്ചറിയലുകൾ വൃത്തിയാക്കും.',

  // Follow-ups
  followUpsTitle: 'വരാനിരിക്കുന്ന ഓർമ്മപ്പെടുത്തലുകൾ',
  userReminderBadge: 'ഉപയോക്തൃ ഓർമ്മപ്പെടുത്തൽ',
  officialDeadlineBadge: 'ഔദ്യോഗിക സമയപരിധി',
  today: 'ഇന്ന്',
  noFollowUps: 'വരാനിരിക്കുന്ന ഓർമ്മപ്പെടുത്തലുകൾ ഷെഡ്യൂൾ ചെയ്തിട്ടില്ല.',
  viewAllFollowUps: 'എല്ലാം കാണുക',
  addReminder: '+ ഓർമ്മപ്പെടുത്തൽ ചേർക്കുക',

  // Trust & Data Freshness
  trustTitle: 'വിശ്വാസ്യതയും വിവരങ്ങളുടെ പുതുമയും',
  recentlyVerified: 'അടുത്തിടെ പരിശോധിച്ചു',
  officialSources: 'ഔദ്യോഗിക സർക്കാർ പോർട്ടലുകൾ',
  nodalSources: 'നിയമപരമായ നോഡൽ ഏജൻസികൾ',
  needsVerification: 'പരിശോധന ബാക്കിയുണ്ട്',
  verifiedOfficialBadge: 'പരിശോധിച്ച ഔദ്യോഗിക സൈറ്റ്',
  knownNodalBadge: 'അംഗീകൃത നോഡൽ പ്ലാറ്റ്ഫോം',
  unverifiedBadge: 'ബാഹ്യ ഉറവിടം',
  statutoryAuditNotice: 'ഗസറ്റുകളും വകുപ്പുതല അറിയിപ്പുകളും അനുസരിച്ച് പരിശോധിച്ചു.',

  // Profile & Assessment
  profileCompleteness: 'പ്രൊഫൈൽ പൂർണ്ണത',
  missingFieldsAlert: 'വിവരങ്ങൾ അപൂർണ്ണമാണ്.',
  completeProfilePrompt: 'നിങ്ങളുടെ പ്രൊഫൈൽ പൂർത്തിയാക്കുന്നത് ശുപാർശകളുടെ കൃത്യത വർദ്ധിപ്പിക്കും.',
  completeProfileBtn: 'പ്രൊഫൈൽ പൂർത്തിയാക്കുക',
  editProfile: 'പ്രൊഫൈൽ എഡിറ്റ് ചെയ്യുക',

  // Empty & Fallback States
  welcomeTitle: 'യോജനാ സേതുവിലേക്ക് സ്വാഗതം',
  welcomeSubtitle: 'വ്യക്തിഗതമാക്കിയ പദ്ധതി ശുപാർശകൾ ലഭിക്കുന്നതിന് നിങ്ങളുടെ ബിസിനസ്സിനെക്കുറിച്ച് ഞങ്ങളോട് പറയുക.',
  buildProfileBtn: 'ബിസിനസ്സ് പ്രൊഫൈൽ സൃഷ്ടിക്കുക',
  noMatchTitle: 'ശക്തമായ പൊരുത്തങ്ങൾ ഇതുവരെ കണ്ടെത്തിയില്ല',
  noMatchSubtitle: 'നിലവിലെ വിവരങ്ങളിൽ നിന്ന് ഉയർന്ന ആത്മവിശ്വാസമുള്ള പദ്ധതിയൊന്നും തിരിച്ചറിയാൻ കഴിഞ്ഞില്ല.',
  reviewProfileBtn: 'പ്രൊഫൈൽ പരിശോധിക്കുക',
  exploreSupportBtn: 'പിന്തുണാ മേഖലകൾ പരിശോധിക്കുക',
  viewNearMatchesBtn: 'അടുത്ത പൊരുത്തങ്ങൾ കാണുക',

  // Modals & Actions
  close: 'അടയ്ക്കുക',
  save: 'സംരക്ഷിക്കുക',
  saved: 'സംരക്ഷിച്ചു',
  confirmSubmissionTitle: 'ഔദ്യോഗിക പോർട്ടൽ സമർപ്പണം സ്ഥിരീകരിക്കുക',
  confirmSubmissionNotice: 'പ്രധാന അറിയിപ്പ്: ഔദ്യോഗിക പോർട്ടൽ തുറക്കുന്നത് നിങ്ങളുടെ അപേക്ഷ യാന്ത്രികമായി സമർപ്പിക്കില്ല. അവരുടെ സൈറ്റിൽ സർക്കാർ പ്രക്രിയ നിങ്ങൾ പൂർത്തിയാക്കണം.',
  confirmSubmissionQuestion: 'നിങ്ങൾ ഔദ്യോഗിക പോർട്ടലിൽ അപേക്ഷ പൂർത്തിയാക്കി സമർപ്പിച്ചോ?',
  confirmYes: 'അതെ, ഞാൻ സമർപ്പിച്ചു',
  confirmNo: 'ഇതുവരെയില്ല, തയ്യാറെടുപ്പിലാണ്',
  portalAcknowledgedPrompt: 'ഔദ്യോഗിക അക്‌നോളഡ്ജ്‌മെന്റ് നമ്പർ നൽകുക (ഓപ്ഷണൽ):',

  // Dashboard 2.0 — Entrepreneur Command Center
  dashSubtitle: 'നിങ്ങളുടെ ശ്രദ്ധ ആവശ്യമുള്ളത് ഇവിടെയുണ്ട്.',
  dashIndicatorReadiness: 'പ്രൊഫൈൽ സജ്ജത',
  dashIndicatorActions: 'തീർപ്പാകാത്ത ജോലികൾ',
  dashIndicatorApplications: 'സജീവമായ അപേക്ഷകൾ',
  dashIndicatorSaved: 'സേവ് ചെയ്ത പദ്ധതികൾ',
  dashContinueJourney: 'നിർത്തിയിടത്ത് നിന്ന് തുടരുക',
  dashExploreMatches: 'എന്റെ പൊരുത്തങ്ങൾ കാണുക',
  dashOpportunitiesTitle: 'മികച്ച അവസരങ്ങൾ',
  dashWhyMatches: 'ഇത് എന്തുകൊണ്ട് പൊരുത്തപ്പെടുന്നു',
  dashViewScheme: 'പദ്ധതി കാണുക →',
  dashPotentiallyRelevant: 'പ്രസക്തമായിരിക്കാം',
  dashJourneyTitle: 'എന്റെ യാത്ര',
  dashCurrentStage: 'നിലവിലെ ഘട്ടം',
  dashStageDISCOVER: 'കണ്ടെത്തുക',
  dashStageMATCH: 'പൊരുത്തപ്പെടുത്തുക',
  dashStageUNDERSTAND: 'മനസ്സിലാക്കുക',
  dashStagePREPARE: 'തയ്യാറാക്കുക',
  dashStageAPPLY: 'അപേക്ഷിക്കുക',
  dashStageTRACK: 'ട്രാക്ക് ചെയ്യുക',
  dashStageLineDISCOVER: 'പ്രസക്തമായ സർക്കാർ സഹായം കണ്ടെത്താൻ നിങ്ങളുടെ ബിസിനസ്സിനെക്കുറിച്ച് പറയുക.',
  dashStageLineMATCH: 'നിങ്ങളുടെ പ്രൊഫൈൽ പരിശോധിച്ചുറപ്പിച്ച പദ്ധതികളുമായി പൊരുത്തപ്പെടുത്തിയിരിക്കുന്നു.',
  dashStageLineUNDERSTAND: 'ഓരോ പദ്ധതിയും എന്ത് നൽകുന്നു, എന്ത് ആവശ്യപ്പെടുന്നു എന്ന് പരിശോധിക്കുക.',
  dashStageLinePREPARE: 'അപേക്ഷിക്കുന്നതിന് മുമ്പ് രേഖകളും വിവരങ്ങളും ശേഖരിക്കുക.',
  dashStageLineAPPLY: 'നിങ്ങളുടെ അപേക്ഷകൾ പുരോഗമിക്കുന്നു.',
  dashStageLineTRACK: 'സമർപ്പിച്ച അപേക്ഷകൾ ഇവിടെ ട്രാക്ക് ചെയ്യുക.',
  dashCtaDISCOVER: 'പദ്ധതി പൊരുത്തത്തോടെ തുടങ്ങുക',
  dashCtaMATCH: 'നിങ്ങളുടെ പൊരുത്തങ്ങൾ പരിശോധിക്കുക',
  dashCtaUNDERSTAND: 'നിങ്ങളുടെ പൊരുത്തങ്ങൾ പര്യവേക്ഷണം ചെയ്യുക',
  dashCtaPREPARE: 'തയ്യാറെടുപ്പ് തുടരുക',
  dashCtaAPPLY: 'അപേക്ഷകൾ കാണുക',
  dashCtaTRACK: 'അപേക്ഷകൾ ട്രാക്ക് ചെയ്യുക',
  dashPrepTitle: 'തയ്യാറെടുപ്പ് കേന്ദ്രം',
  dashPrepDocuments: 'രേഖകൾ',
  dashPrepFinancial: 'സാമ്പത്തിക പ്രൊഫൈൽ',
  dashPrepRegistrations: 'ബിസിനസ്സ് രജിസ്ട്രേഷനുകൾ',
  dashPrepPortal: 'ഔദ്യോഗിക സമർപ്പണം',
  dashPrepComplete: 'പൂർണ്ണം',
  dashPrepAttention: 'ശ്രദ്ധ ആവശ്യമാണ്',
  dashPrepNotAssessed: 'ഇതുവരെ വിലയിരുത്തിയിട്ടില്ല',
  dashPrepPortalAvailable: 'ഔദ്യോഗിക പോർട്ടൽ ലഭ്യമാണ്',
  dashPrepOpenWorkspace: 'തയ്യാറെടുപ്പ് വർക്ക്സ്പേസ് തുറക്കുക',
  dashStatMatches: 'പൊരുത്തങ്ങൾ',
  dashStatMatchesDesc: 'നിങ്ങളുടെ പ്രൊഫൈലുമായി പൊരുത്തപ്പെടുന്ന പദ്ധതികൾ',
  dashStatMatchesAction: 'പൊരുത്തങ്ങൾ കാണുക',
  dashStatApplications: 'അപേക്ഷകൾ',
  dashStatApplicationsDesc: 'പുരോഗതിയിലുള്ളതോ സമർപ്പിച്ചതോ',
  dashStatApplicationsAction: 'അപേക്ഷകൾ കാണുക',
  dashStatSaved: 'സേവ് ചെയ്തവ',
  dashStatSavedDesc: 'നിങ്ങൾ ബുക്ക്മാർക്ക് ചെയ്ത പദ്ധതികൾ',
  dashStatSavedAction: 'സേവ് ചെയ്തവ കാണുക',
  dashStatReadiness: 'സജ്ജത',
  dashStatReadinessDesc: 'പ്രൊഫൈൽ പൂർണ്ണത',
  dashStatReadinessAction: 'പ്രൊഫൈൽ പൂർത്തിയാക്കുക',
  dashApplicationsTitle: 'അപേക്ഷകൾ',
  dashApplicationsEmpty: 'നിങ്ങൾ തയ്യാറാക്കാൻ തുടങ്ങുന്ന അപേക്ഷകൾ ഇവിടെ കാണിക്കും.',
  dashViewApplications: 'അപേക്ഷകൾ കാണുക',
  dashExploreYourMatches: 'നിങ്ങളുടെ പൊരുത്തങ്ങൾ പര്യവേക്ഷണം ചെയ്യുക',
  dashSavedTitle: 'സേവ് ചെയ്ത പദ്ധതികൾ',
  dashSchemesSaved: 'പദ്ധതികൾ സേവ് ചെയ്തു',
  dashSavedEmpty: 'നിങ്ങൾ ഇതുവരെ ഒരു പദ്ധതിയും സേവ് ചെയ്തിട്ടില്ല.',
  dashViewAllSaved: 'സേവ് ചെയ്ത എല്ലാ പദ്ധതികളും കാണുക →',
  dashReadinessTitle: 'പ്രൊഫൈൽ സജ്ജത',
  dashReadinessPersonal: 'വ്യക്തിപരം',
  dashReadinessBusiness: 'ബിസിനസ്സ്',
  dashReadinessFinancial: 'സാമ്പത്തികം',
  dashReadinessRegistrations: 'രജിസ്ട്രേഷനുകൾ',
  dashReadinessDocuments: 'രേഖകൾ',
  dashStateComplete: 'പൂർണ്ണം',
  dashStateAttention: 'ശ്രദ്ധ ആവശ്യമാണ്',
  dashStateNotAssessed: 'ഇതുവരെ വിലയിരുത്തിയിട്ടില്ല',
  dashCompleteProfile: 'പ്രൊഫൈൽ പൂർത്തിയാക്കുക →',
  dashTrustTitle: 'ഡാറ്റയും വിശ്വാസവും',
  dashTrustBasedOn: 'ശുപാർശകൾ ഇവയെ അടിസ്ഥാനമാക്കിയുള്ളതാണ്:',
  dashTrustProfile: 'നിങ്ങളുടെ പ്രൊഫൈൽ',
  dashTrustDeterministic: 'നിർണ്ണായക പൊരുത്തപ്പെടുത്തൽ',
  dashTrustSource: 'പദ്ധതി ഉറവിട വിവരം',
  dashActivityTitle: 'സമീപകാല പ്രവർത്തനം',
  dashReadinessIntro: 'അഞ്ച് മേഖലകളിലും നിങ്ങളുടെ പ്രൊഫൈലിന്റെ ദ്രുത വീക്ഷണം.',
  dashViewProfile: 'പ്രൊഫൈൽ കാണുക',
  dashActivityEmpty: 'നിങ്ങൾ ആരംഭിച്ചുകഴിഞ്ഞാൽ നിങ്ങളുടെ സമീപകാല പ്രവർത്തനം ഇവിടെ ദൃശ്യമാകും.',
  dashRemoveSaved: 'സേവ് ചെയ്തതിൽ നിന്ന് നീക്കം ചെയ്യുക',
  dashTrustIntro: 'നിങ്ങളുടെ മുൻനിര അവസരങ്ങൾക്കുള്ള വിശ്വാസ സൂചനകൾ, പദ്ധതി ഉറവിടത്തിൽ നിന്ന് പരിശോധിച്ചത്.',
};
