/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const mr = {
  // Navigation & Branding
  brandName: 'योजना सेतु',
  brandTagline: 'बुद्धिमान उद्योजक कमांड सेंटर',
  navHome: 'कमांड सेंटर',
  navSchemes: 'योजना',
  navApplications: 'अर्ज',
  navDocuments: 'कागदपत्रे',
  navProfile: 'व्यवसाय प्रोफाइल',

  // Greetings & Header
  greetingMorning: 'सुप्रभात.',
  greetingAfternoon: 'शुभ दुपार.',
  greetingEvening: 'शुभ संध्याकाळ.',
  headerSubtitle: 'आज आपल्या व्यवसायासाठी जे महत्त्वाचे आहे, ते येथे आहे.',
  headerSubtitleEmpty: 'आपल्या व्यवसाय समर्थन प्रवासाची सध्याची स्थिती येथे दिसेल.',

  // Next Best Action
  nextBestActionTitle: 'पुढील सर्वोत्तम कृती',
  continueAction: 'पुढे चालू ठेवा →',
  exploreAction: 'पहा →',

  // Business Journey
  businessJourneyTitle: 'आपली व्यवसाय यात्रा',
  currentFocus: 'सध्याचे लक्ष्य',
  relevantSchemes: 'संबंधित योजना',
  supportPathways: 'समर्थन मार्ग',
  applicationUnderway: 'अर्ज प्रक्रिया सुरू आहे',
  applicationsUnderway: 'अर्ज प्रक्रिया सुरू आहेत',
  exploreCategory: 'पहा',

  // Opportunities
  topOpportunitiesTitle: 'शीर्ष संधी',
  topOpportunityHeading: 'शीर्ष संधी',
  matchScoreLabel: 'जुळणी',
  actionNowBadge: 'आत्ताच कृती करा',
  highPriorityBadge: 'उच्च प्राधान्य',
  reviewBadge: 'आढावा',
  infoNeededBadge: 'माहिती आवश्यक',
  lowPriorityBadge: 'कमी प्राधान्य',
  whyThisSchemeTitle: 'ही योजना का — आणि आत्ताच का?',
  eligibilityReviewed: 'पात्रतेचा आढावा घेतला',
  financialFit: 'आर्थिक जुळणी',
  stateSupported: 'राज्य समर्थित',
  documentsPrepared: 'कागदपत्रे तयार',
  readyToReview: 'आढाव्यासाठी तयार',
  informationNeededText: 'माहिती आवश्यक',
  continueApplication: 'अर्ज पुढे चालू ठेवा →',
  openOfficialPortal: 'अधिकृत पोर्टल उघडा ↗',

  // Applications
  applicationsTitle: 'आपले अर्ज',
  readyToApply: 'अर्जासाठी तयार',
  preparing: 'तयारी सुरू',
  applied: 'अर्ज केला',
  approved: 'मंजूर',
  interested: 'स्वारस्य',
  viewApplications: 'सर्व अर्ज पाहा →',
  noApplicationsYet: 'सक्रिय अर्ज नाहीत. आपल्या शीर्ष संधीची तयारी करून सुरुवात करा.',

  // Documents
  documentCenterTitle: 'कागदपत्र केंद्र',
  prepared: 'तयार',
  needPreparation: 'तयारी आवश्यक',
  unknown: 'अज्ञात',
  notRequired: 'आवश्यक नाही',
  reusableDocuments: 'पुन्हा वापरता येणारी कागदपत्रे',
  applicationSpecificDocuments: 'अर्जविशिष्ट कागदपत्रे',
  viewDocumentCenter: 'कागदपत्र केंद्र पाहा →',
  privacyGuarantee: 'खाजगी आणि सुरक्षित: योजना सेतु ओळख क्रमांक, पासवर्ड किंवा बँक तपशील कधीही मागत नाही आणि साठवणीपूर्वी संवेदनशील ओळखकर्ता स्वच्छ करते.',

  // Follow-ups
  followUpsTitle: 'आगामी पाठपुरावे',
  userReminderBadge: 'वापरकर्ता स्मरणपत्र',
  officialDeadlineBadge: 'अधिकृत अंतिम मुदत',
  today: 'आज',
  noFollowUps: 'कोणतेही आगामी पाठपुरावे नियोजित नाहीत.',
  viewAllFollowUps: 'सर्व पाहा →',
  addReminder: '+ स्मरणपत्र जोडा',

  // Trust & Data Freshness
  trustTitle: 'विश्वास आणि डेटा ताजेपणा',
  recentlyVerified: 'अलीकडेच सत्यापित',
  officialSources: 'अधिकृत शासकीय पोर्टल',
  nodalSources: 'वैधानिक नोडल संस्था',
  needsVerification: 'लेखापरीक्षण प्रलंबित',
  verifiedOfficialBadge: 'सत्यापित अधिकृत',
  knownNodalBadge: 'ज्ञात नोडल प्लॅटफॉर्म',
  unverifiedBadge: 'बाह्य स्रोत',
  statutoryAuditNotice: 'अधिकृत राजपत्रे आणि विभागीय अधिसूचनांशी लेखापरीक्षण केले आहे.',

  // Profile & Assessment
  profileCompleteness: 'प्रोफाइल पूर्णता',
  missingFieldsAlert: 'माहितीचे तुकडे गहाळ आहेत.',
  completeProfilePrompt: 'आपला प्रोफाइल पूर्ण केल्याने शिफारशींची अचूकता सुधारू शकते.',
  completeProfileBtn: 'प्रोफाइल पूर्ण करा →',
  editProfile: 'प्रोफाइल संपादित करा',

  // Empty & Fallback States
  welcomeTitle: 'योजना सेतुमध्ये आपले स्वागत आहे',
  welcomeSubtitle: 'वैयक्तिकृत योजना शिफारसींसाठी आपल्या व्यवसायाबद्दल आम्हाला सांगा.',
  buildProfileBtn: 'माझा व्यवसाय प्रोफाइल तयार करा →',
  noMatchTitle: 'अद्याप ठोस जुळणी नाही',
  noMatchSubtitle: 'सध्या उपलब्ध असलेल्या माहितीवरून उच्च-आत्मविश्वास असलेली योजना ओळखता आली नाही.',
  reviewProfileBtn: 'प्रोफाइलचा आढावा घ्या',
  exploreSupportBtn: 'समर्थन क्षेत्रे पहा',
  viewNearMatchesBtn: 'जवळच्या जुळण्या पाहा',

  // Modals & Actions
  close: 'बंद करा',
  save: 'जतन करा',
  saved: 'जतन केले',
  confirmSubmissionTitle: 'अधिकृत पोर्टल सबमिशनची पुष्टी करा',
  confirmSubmissionNotice: 'महत्त्वाचे: अधिकृत पोर्टल उघडल्याने आपला अर्ज आपोआप सादर होत नाही. त्यांच्या साइटवर शासकीय प्रक्रिया पूर्ण करणे आवश्यक आहे.',
  confirmSubmissionQuestion: 'आपण अधिकृत पोर्टलवर आपला अर्ज पूर्ण करून सादर केला आहे का?',
  confirmYes: 'होय, मी सादर केला आहे',
  confirmNo: 'अद्याप नाही, तयारी सुरू आहे',
  portalAcknowledgedPrompt: 'अधिकृत पोच क्रमांक प्रविष्ट करा (पर्यायी):',

  // Dashboard 2.0 — Entrepreneur Command Center
  dashSubtitle: 'तुमच्या लक्ष देण्याजोग्या गोष्टी येथे आहेत.',
  dashIndicatorReadiness: 'प्रोफाइल सज्जता',
  dashIndicatorActions: 'प्रलंबित कामे',
  dashIndicatorApplications: 'सक्रिय अर्ज',
  dashIndicatorSaved: 'जतन केलेल्या योजना',
  dashContinueJourney: 'सोडलेल्या ठिकाणाहून पुढे सुरू करा →',
  dashExploreMatches: 'माझ्या जुळण्या पहा →',
  dashOpportunitiesTitle: 'शीर्ष संधी',
  dashWhyMatches: 'हे का जुळते',
  dashViewScheme: 'योजना पहा →',
  dashPotentiallyRelevant: 'संभाव्यतः संबंधित',
  dashJourneyTitle: 'माझा प्रवास',
  dashCurrentStage: 'सध्याचा टप्पा',
  dashStageDISCOVER: 'शोधा',
  dashStageMATCH: 'जुळवा',
  dashStageUNDERSTAND: 'समजा',
  dashStagePREPARE: 'तयारी करा',
  dashStageAPPLY: 'अर्ज करा',
  dashStageTRACK: 'मागोवा घ्या',
  dashStageLineDISCOVER: 'संबंधित शासकीय सहाय्य शोधण्यासाठी तुमच्या व्यवसायाबद्दल सांगा.',
  dashStageLineMATCH: 'तुमचे प्रोफाइल सत्यापित योजनांशी जुळवले गेले आहे.',
  dashStageLineUNDERSTAND: 'प्रत्येक योजना काय देते आणि काय मागते याचा आढावा घ्या.',
  dashStageLinePREPARE: 'अर्ज करण्यापूर्वी तुमची कागदपत्रे आणि तपशील गोळा करा.',
  dashStageLineAPPLY: 'तुमचे अर्ज प्रगतीपथावर आहेत.',
  dashStageLineTRACK: 'सादर केलेल्या अर्जांचा येथे मागोवा घ्या.',
  dashCtaDISCOVER: 'योजना जुळणीपासून सुरुवात करा →',
  dashCtaMATCH: 'तुमच्या जुळण्यांचा आढावा घ्या →',
  dashCtaUNDERSTAND: 'तुमच्या जुळण्या एक्स्प्लोर करा →',
  dashCtaPREPARE: 'तयारी सुरू ठेवा →',
  dashCtaAPPLY: 'अर्ज पहा →',
  dashCtaTRACK: 'अर्जांचा मागोवा घ्या →',
  dashPrepTitle: 'तयारी केंद्र',
  dashPrepDocuments: 'कागदपत्रे',
  dashPrepFinancial: 'आर्थिक प्रोफाइल',
  dashPrepRegistrations: 'व्यवसाय नोंदणी',
  dashPrepPortal: 'अधिकृत सादरीकरण',
  dashPrepComplete: 'पूर्ण',
  dashPrepAttention: 'लक्ष आवश्यक',
  dashPrepNotAssessed: 'अद्याप मूल्यांकन नाही',
  dashPrepPortalAvailable: 'अधिकृत पोर्टल उपलब्ध',
  dashPrepOpenWorkspace: 'तयारी कार्यक्षेत्र उघडा →',
  dashApplicationsTitle: 'अर्ज',
  dashApplicationsEmpty: 'तुम्ही तयार करण्यास सुरुवात कराल ते अर्ज येथे दिसतील.',
  dashViewApplications: 'अर्ज पहा →',
  dashExploreYourMatches: 'तुमच्या जुळण्या एक्स्प्लोर करा →',
  dashSavedTitle: 'जतन केलेल्या योजना',
  dashSchemesSaved: 'योजना जतन केल्या',
  dashSavedEmpty: 'तुम्ही अद्याप कोणतीही योजना जतन केलेली नाही.',
  dashViewAllSaved: 'जतन केलेल्या सर्व योजना पहा →',
  dashReadinessTitle: 'प्रोफाइल सज्जता',
  dashReadinessPersonal: 'वैयक्तिक',
  dashReadinessBusiness: 'व्यवसाय',
  dashReadinessFinancial: 'आर्थिक',
  dashReadinessRegistrations: 'नोंदणी',
  dashReadinessDocuments: 'कागदपत्रे',
  dashStateComplete: 'पूर्ण',
  dashStateAttention: 'लक्ष आवश्यक',
  dashStateNotAssessed: 'अद्याप मूल्यांकन नाही',
  dashCompleteProfile: 'प्रोफाइल पूर्ण करा →',
  dashTrustTitle: 'डेटा आणि विश्वास',
  dashTrustBasedOn: 'शिफारसी यावर आधारित आहेत:',
  dashTrustProfile: 'तुमचे प्रोफाइल',
  dashTrustDeterministic: 'निश्चित जुळणी',
  dashTrustSource: 'योजना स्रोत माहिती',
  dashActivityTitle: 'अलीकडील क्रियाकलाप',
  dashReadinessIntro: 'पाचही क्षेत्रांतील तुमच्या प्रोफाइलचे त्वरित विहंगावलोकन.',
  dashViewProfile: 'प्रोफाइल पहा →',
  dashActivityEmpty: 'तुम्ही सुरुवात केल्यावर तुमची अलीकडील क्रियाकलाप येथे दिसेल.',
  dashRemoveSaved: 'जतन केलेल्यांमधून काढा',
  dashTrustIntro: 'तुमच्या प्रमुख संधींसाठी विश्वास संकेत, योजना स्रोताकडून सत्यापित.',
};
