/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const ta = {
  // Navigation & Branding
  brandName: 'யோஜனா சேது',
  brandTagline: 'அறிவுசார் தொழில்முனைவோர் கட்டளை மையம்',
  navHome: 'கட்டளை மையம்',
  navSchemes: 'திட்டங்கள்',
  navApplications: 'விண்ணப்பங்கள்',
  navDocuments: 'ஆவணங்கள்',
  navProfile: 'வணிக சுயவிவரம்',

  // Greetings & Header
  greetingMorning: 'காலை வணக்கம்.',
  greetingAfternoon: 'மதிய வணக்கம்.',
  greetingEvening: 'மாலை வணக்கம்.',
  headerSubtitle: 'இன்று உங்கள் வணிகத்திற்கு முக்கியமானவை இங்கே உள்ளன.',
  headerSubtitleEmpty: 'உங்கள் வணிக ஆதரவுப் பயணத்தின் தற்போதைய நிலை இங்கே.',

  // Next Best Action
  nextBestActionTitle: 'அடுத்த சிறந்த நடவடிக்கை',
  continueAction: 'தொடர்க →',
  exploreAction: 'ஆராய்க →',

  // Business Journey
  businessJourneyTitle: 'உங்கள் வணிகப் பயணம்',
  currentFocus: 'தற்போதைய கவனம்',
  relevantSchemes: 'பொருத்தமான திட்டங்கள்',
  supportPathways: 'ஆதரவு வழிகள்',
  applicationUnderway: 'விண்ணப்பம் செயல்பாட்டில் உள்ளது',
  applicationsUnderway: 'விண்ணப்பங்கள் செயல்பாட்டில் உள்ளன',
  exploreCategory: 'ஆராய்க',

  // Opportunities
  topOpportunitiesTitle: 'முதன்மை வாய்ப்புகள்',
  topOpportunityHeading: 'முதன்மை வாய்ப்பு',
  matchScoreLabel: 'பொருத்தம்',
  actionNowBadge: 'உடனடி நடவடிக்கை',
  highPriorityBadge: 'உயர் முன்னுரிமை',
  reviewBadge: 'மறுஆய்வு',
  infoNeededBadge: 'தகவல் தேவை',
  lowPriorityBadge: 'குறைந்த முன்னுரிமை',
  whyThisSchemeTitle: 'ஏன் இந்தத் திட்டம் — ஏன் இப்போது?',
  eligibilityReviewed: 'தகுதி மதிப்பாய்வு செய்யப்பட்டது',
  financialFit: 'நிதிப் பொருத்தம்',
  stateSupported: 'மாநில அரசு ஆதரவு',
  documentsPrepared: 'ஆவணங்கள் தயார்',
  readyToReview: 'மறுஆய்வுக்குத் தயார்',
  informationNeededText: 'தகவல் தேவைப்படுகிறது',
  continueApplication: 'விண்ணப்பத்தைத் தொடர்க',
  openOfficialPortal: 'அதிகாரப்பூர்வ போர்ட்டலைத் திறக்குக ↗',

  // Applications
  applicationsTitle: 'உங்கள் விண்ணப்பங்கள்',
  readyToApply: 'விண்ணப்பிக்கத் தயார்',
  preparing: 'தயாராகிறது',
  applied: 'விண்ணப்பிக்கப்பட்டது',
  approved: 'ஒப்புதல் அளிக்கப்பட்டது',
  interested: 'ஆர்வமுள்ளவை',
  viewApplications: 'அனைத்து விண்ணப்பங்களையும் காண்க',
  noApplicationsYet: 'செயலில் உள்ள விண்ணப்பங்கள் எதுவும் இல்லை. உங்கள் முதன்மை வாய்ப்பைத் தயார் செய்வதன் மூலம் தொடங்கவும்.',

  // Documents
  documentCenterTitle: 'ஆவண மையம்',
  prepared: 'தயார்',
  needPreparation: 'தயாரிப்பு தேவை',
  unknown: 'தெரியவில்லை',
  notRequired: 'தேவையில்லை',
  reusableDocuments: 'மறுபயன்பாட்டு ஆவணங்கள்',
  applicationSpecificDocuments: 'திட்டம் சார்ந்த ஆவணங்கள்',
  viewDocumentCenter: 'ஆவண மையத்தைக் காண்க',
  privacyGuarantee: 'பாதுகாப்பானது: யோஜனா சேது அடையாள எண்கள், கடவுச்சொற்கள் அல்லது வங்கி விவரங்களை ஒருபோதும் கேட்காது; சேமிப்பிற்கு முன் உணர்திறன் அடையாளங்கள் சுத்தம் செய்யப்படும்.',

  // Follow-ups
  followUpsTitle: 'வரவிருக்கும் நினைவூட்டல்கள்',
  userReminderBadge: 'பயனர் நினைவூட்டல்',
  officialDeadlineBadge: 'அதிகாரப்பூர்வ காலக்கெடு',
  today: 'இன்று',
  noFollowUps: 'வரவிருக்கும் நினைவூட்டல்கள் எதுவும் இல்லை.',
  viewAllFollowUps: 'அனைத்தையும் காண்க',
  addReminder: '+ நினைவூட்டலைச் சேர்க்க',

  // Trust & Data Freshness
  trustTitle: 'நம்பகத்தன்மை & தரவு புதுப்பிப்பு',
  recentlyVerified: 'சமீபத்தில் சரிபார்க்கப்பட்டது',
  officialSources: 'அதிகாரப்பூர்வ அரசு போர்ட்டல்கள்',
  nodalSources: 'சட்டரீதியான நோடல் முகமைகள்',
  needsVerification: 'தணிக்கை நிலுவையில் உள்ளது',
  verifiedOfficialBadge: 'சரிபார்க்கப்பட்ட அதிகாரப்பூர்வ தளம்',
  knownNodalBadge: 'அங்கீகரிக்கப்பட்ட நோடல் தளம்',
  unverifiedBadge: 'வெளிப்புற மூலம்',
  statutoryAuditNotice: 'அரசிதழ்கள் மற்றும் துறைசார் அறிவிப்புகளின்படி தணிக்கை செய்யப்பட்டது.',

  // Profile & Assessment
  profileCompleteness: 'சுயவிவர முழுமை',
  missingFieldsAlert: 'தகவல்கள் விடுபட்டுள்ளன.',
  completeProfilePrompt: 'உங்கள் சுயவிவரத்தைப் பூர்த்தி செய்வது பரிந்துரை துல்லியத்தை மேம்படுத்தும்.',
  completeProfileBtn: 'சுயவிவரத்தைப் பூர்த்தி செய்க',
  editProfile: 'சுயவிவரத்தைத் திருத்துக',

  // Empty & Fallback States
  welcomeTitle: 'யோஜனா சேதுவிற்கு நல்வரவு',
  welcomeSubtitle: 'தனிப்பயனாக்கப்பட்ட திட்டப் பரிந்துரைகளைப் பெற உங்கள் வணிகத்தைப் பற்றி எங்களிடம் கூறுங்கள்.',
  buildProfileBtn: 'வணிக சுயவிவரத்தை உருவாக்குக',
  noMatchTitle: 'இன்னும் வலுவான பொருத்தங்கள் கிடைக்கவில்லை',
  noMatchSubtitle: 'தற்போது கிடைக்கும் தகவல்களிலிருந்து உயர்-நம்பகத்தன்மை கொண்ட திட்டத்தை எங்களால் அடையாளம் காண முடியவில்லை.',
  reviewProfileBtn: 'சுயவிவரத்தை மறுஆய்வு செய்க',
  exploreSupportBtn: 'ஆதரவுப் பகுதிகளை ஆராய்க',
  viewNearMatchesBtn: 'நெருங்கிய பொருத்தங்களைக் காண்க',

  // Modals & Actions
  close: 'மூடுக',
  save: 'சேமிக்க',
  saved: 'சேமிக்கப்பட்டது',
  confirmSubmissionTitle: 'அதிகாரப்பூர்வ போர்ட்டல் சமர்ப்பிப்பை உறுதிசெய்க',
  confirmSubmissionNotice: 'முக்கிய குறிப்பு: அதிகாரப்பூர்வ போர்ட்டலைத் திறப்பது உங்கள் விண்ணப்பத்தைத் தானாகவே சமர்ப்பிக்காது. அந்த தளத்தில் அரசு நடைமுறையை நீங்கள் முடிக்க வேண்டும்.',
  confirmSubmissionQuestion: 'அதிகாரப்பூர்வ போர்ட்டலில் உங்கள் விண்ணப்பத்தைப் பூர்த்தி செய்து சமர்ப்பித்துவிட்டீர்களா?',
  confirmYes: 'ஆம், நான் சமர்ப்பித்துவிட்டேன்',
  confirmNo: 'இல்லை, இன்னும் தயாராகிறேன்',
  portalAcknowledgedPrompt: 'அதிகாரப்பூர்வ ஒப்புதல் எண்ணை உள்ளிடவும் (விருப்பத்தேர்வு):',

  // Dashboard 2.0 — Entrepreneur Command Center
  dashSubtitle: 'உங்கள் கவனம் தேவைப்படுபவை இங்கே.',
  dashIndicatorReadiness: 'சுயவிவர தயார்நிலை',
  dashIndicatorActions: 'நிலுவை பணிகள்',
  dashIndicatorApplications: 'செயலில் உள்ள விண்ணப்பங்கள்',
  dashIndicatorSaved: 'சேமித்த திட்டங்கள்',
  dashContinueJourney: 'விட்ட இடத்திலிருந்து தொடரவும்',
  dashExploreMatches: 'என் பொருத்தங்களைப் பார்க்கவும்',
  dashOpportunitiesTitle: 'முக்கிய வாய்ப்புகள்',
  dashWhyMatches: 'இது ஏன் பொருந்துகிறது',
  dashViewScheme: 'திட்டத்தைப் பார்க்க →',
  dashPotentiallyRelevant: 'பொருத்தமாக இருக்கலாம்',
  dashJourneyTitle: 'என் பயணம்',
  dashCurrentStage: 'தற்போதைய நிலை',
  dashStageDISCOVER: 'கண்டறி',
  dashStageMATCH: 'பொருத்து',
  dashStageUNDERSTAND: 'புரிந்துகொள்',
  dashStagePREPARE: 'தயார் செய்',
  dashStageAPPLY: 'விண்ணப்பி',
  dashStageTRACK: 'கண்காணி',
  dashStageLineDISCOVER: 'தொடர்புடைய அரசு ஆதரவைக் கண்டறிய உங்கள் வணிகம் பற்றி கூறுங்கள்.',
  dashStageLineMATCH: 'உங்கள் சுயவிவரம் சரிபார்க்கப்பட்ட திட்டங்களுடன் பொருத்தப்பட்டுள்ளது.',
  dashStageLineUNDERSTAND: 'ஒவ்வொரு திட்டமும் என்ன வழங்குகிறது, என்ன கேட்கிறது என்பதை மதிப்பாய்வு செய்யுங்கள்.',
  dashStageLinePREPARE: 'விண்ணப்பிக்கும் முன் உங்கள் ஆவணங்களையும் விவரங்களையும் திரட்டுங்கள்.',
  dashStageLineAPPLY: 'உங்கள் விண்ணப்பங்கள் நடைபெற்று வருகின்றன.',
  dashStageLineTRACK: 'சமர்ப்பித்த விண்ணப்பங்களை இங்கே கண்காணியுங்கள்.',
  dashCtaDISCOVER: 'திட்டப் பொருத்தத்துடன் தொடங்குங்கள்',
  dashCtaMATCH: 'உங்கள் பொருத்தங்களை மதிப்பாய்வு செய்யுங்கள்',
  dashCtaUNDERSTAND: 'உங்கள் பொருத்தங்களை ஆராயுங்கள்',
  dashCtaPREPARE: 'தயாரிப்பைத் தொடரவும்',
  dashCtaAPPLY: 'விண்ணப்பங்களைப் பார்க்கவும்',
  dashCtaTRACK: 'விண்ணப்பங்களைக் கண்காணியுங்கள்',
  dashPrepTitle: 'தயாரிப்பு மையம்',
  dashPrepDocuments: 'ஆவணங்கள்',
  dashPrepFinancial: 'நிதி சுயவிவரம்',
  dashPrepRegistrations: 'வணிகப் பதிவுகள்',
  dashPrepPortal: 'அதிகாரப்பூர்வ சமர்ப்பிப்பு',
  dashPrepComplete: 'முழுமை',
  dashPrepAttention: 'கவனம் தேவை',
  dashPrepNotAssessed: 'இன்னும் மதிப்பிடப்படவில்லை',
  dashPrepPortalAvailable: 'அதிகாரப்பூர்வ போர்ட்டல் உள்ளது',
  dashPrepOpenWorkspace: 'தயாரிப்பு பணியிடத்தைத் திற',
  dashStatMatches: 'பொருத்தங்கள்',
  dashStatMatchesDesc: 'உங்கள் சுயவிவரத்துடன் பொருந்தும் திட்டங்கள்',
  dashStatMatchesAction: 'பொருத்தங்களைக் காண்க',
  dashStatApplications: 'விண்ணப்பங்கள்',
  dashStatApplicationsDesc: 'நடந்து கொண்டிருக்கும் அல்லது சமர்ப்பிக்கப்பட்டவை',
  dashStatApplicationsAction: 'விண்ணப்பங்களைக் காண்க',
  dashStatSaved: 'சேமித்தவை',
  dashStatSavedDesc: 'நீங்கள் புக்மார்க் செய்த திட்டங்கள்',
  dashStatSavedAction: 'சேமித்தவற்றைக் காண்க',
  dashStatReadiness: 'தயார்நிலை',
  dashStatReadinessDesc: 'சுயவிவர முழுமை',
  dashStatReadinessAction: 'சுயவிவரத்தை நிறைவு செய்க',
  dashApplicationsTitle: 'விண்ணப்பங்கள்',
  dashApplicationsEmpty: 'நீங்கள் தயாரிக்கத் தொடங்கும் விண்ணப்பங்கள் இங்கே தோன்றும்.',
  dashViewApplications: 'விண்ணப்பங்களைப் பார்க்கவும்',
  dashExploreYourMatches: 'உங்கள் பொருத்தங்களை ஆராயுங்கள்',
  dashSavedTitle: 'சேமித்த திட்டங்கள்',
  dashSchemesSaved: 'திட்டங்கள் சேமிக்கப்பட்டன',
  dashSavedEmpty: 'நீங்கள் இன்னும் எந்தத் திட்டத்தையும் சேமிக்கவில்லை.',
  dashViewAllSaved: 'சேமித்த அனைத்துத் திட்டங்களையும் பார்க்கவும் →',
  dashReadinessTitle: 'சுயவிவர தயார்நிலை',
  dashReadinessPersonal: 'தனிப்பட்ட',
  dashReadinessBusiness: 'வணிக',
  dashReadinessFinancial: 'நிதி',
  dashReadinessRegistrations: 'பதிவுகள்',
  dashReadinessDocuments: 'ஆவணங்கள்',
  dashStateComplete: 'முழுமை',
  dashStateAttention: 'கவனம் தேவை',
  dashStateNotAssessed: 'இன்னும் மதிப்பிடப்படவில்லை',
  dashCompleteProfile: 'சுயவிவரத்தை நிறைவு செய்யுங்கள் →',
  dashTrustTitle: 'தரவு & நம்பிக்கை',
  dashTrustBasedOn: 'பரிந்துரைகள் இவற்றை அடிப்படையாகக் கொண்டவை:',
  dashTrustProfile: 'உங்கள் சுயவிவரம்',
  dashTrustDeterministic: 'தீர்மானகரமான பொருத்தம்',
  dashTrustSource: 'திட்ட மூலத் தகவல்',
  dashActivityTitle: 'சமீபத்திய செயல்பாடு',
  dashReadinessIntro: 'ஐந்து பகுதிகளிலும் உங்கள் சுயவிவரத்தின் விரைவான பார்வை.',
  dashViewProfile: 'சுயவிவரத்தைப் பார்க்க',
  dashActivityEmpty: 'நீங்கள் தொடங்கியதும் உங்கள் சமீபத்திய செயல்பாடு இங்கே தோன்றும்.',
  dashRemoveSaved: 'சேமித்தவற்றிலிருந்து நீக்கு',
  dashTrustIntro: 'உங்கள் முக்கிய வாய்ப்புகளுக்கான நம்பிக்கை சமிக்ஞைகள், திட்ட மூலத்திலிருந்து சரிபார்க்கப்பட்டவை.',
};
