/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const te = {
  // Navigation & Branding
  brandName: 'యోజనా సేతు',
  brandTagline: 'ఇంటెలిజెంట్ వ్యవస్థాపక కమాండ్ సెంటర్',
  navHome: 'కమాండ్ సెంటర్',
  navSchemes: 'పథకాలు',
  navApplications: 'దరఖాస్తులు',
  navDocuments: 'పత్రాలు',
  navProfile: 'వ్యాపార ప్రొఫైల్',

  // Greetings & Header
  greetingMorning: 'శుభోదయం.',
  greetingAfternoon: 'శుభ మధ్యాహ్నం.',
  greetingEvening: 'శుభ సాయంత్రం.',
  headerSubtitle: 'ఈ రోజు మీ వ్యాపారానికి అవసరమైన ముఖ్యమైన అంశాలు ఇక్కడ ఉన్నాయి.',
  headerSubtitleEmpty: 'మీ వ్యాపార సహాయ ప్రయాణం ప్రస్తుత స్థితి ఇక్కడ ఉంది.',

  // Next Best Action
  nextBestActionTitle: 'తదుపరి ఉత్తమ చర్య',
  continueAction: 'కొనసాగించండి →',
  exploreAction: 'అన్వేషించండి →',

  // Business Journey
  businessJourneyTitle: 'మీ వ్యాపార ప్రయాణం',
  currentFocus: 'ప్రస్తుత దృష్టి',
  relevantSchemes: 'సంబంధిత పథకాలు',
  supportPathways: 'సహాయ మార్గాలు',
  applicationUnderway: 'దరఖాస్తు ప్రక్రియలో ఉంది',
  applicationsUnderway: 'దరఖాస్తులు ప్రక్రియలో ఉన్నాయి',
  exploreCategory: 'అన్వేషించండి',

  // Opportunities
  topOpportunitiesTitle: 'అగ్ర అవకాశాలు',
  topOpportunityHeading: 'అగ్ర అవకాశం',
  matchScoreLabel: 'సరిపోలిక',
  actionNowBadge: 'వెంటనే చర్య తీసుకోండి',
  highPriorityBadge: 'అధిక ప్రాధాన్యత',
  reviewBadge: 'సమీక్షించండి',
  infoNeededBadge: 'సమాచారం అవసరం',
  lowPriorityBadge: 'తక్కువ ప్రాధాన్యత',
  whyThisSchemeTitle: 'ఈ పథకం ఎందుకు — ఇప్పుడే ఎందుకు?',
  eligibilityReviewed: 'అర్హత సమీక్షించబడింది',
  financialFit: 'ఆర్థిక సరిపోలిక',
  stateSupported: 'రాష్ట్ర ప్రభుత్వ మద్దతు',
  documentsPrepared: 'పత్రాలు సిద్ధంగా ఉన్నాయి',
  readyToReview: 'సమీక్షకు సిద్ధంగా ఉంది',
  informationNeededText: 'సమాచారం అవసరం',
  continueApplication: 'దరఖాస్తును కొనసాగించండి →',
  openOfficialPortal: 'అధికారిక పోర్టల్ తెరవండి ↗',

  // Applications
  applicationsTitle: 'మీ దరఖాస్తులు',
  readyToApply: 'దరఖాస్తు చేయడానికి సిద్ధంగా ఉంది',
  preparing: 'సిద్ధమవుతోంది',
  applied: 'దరఖాస్తు చేయబడింది',
  approved: 'ఆమోదించబడింది',
  interested: 'ఆసక్తి చూపబడింది',
  viewApplications: 'అన్ని దరఖాస్తులను వీక్షించండి →',
  noApplicationsYet: 'క్రియాశీల దరఖాస్తులు ఏవీ లేవు. మీ అగ్ర అవకాశాన్ని సిద్ధం చేయడం ద్వారా ప్రారంభించండి.',

  // Documents
  documentCenterTitle: 'పత్రాల కేంద్రం',
  prepared: 'సిద్ధం',
  needPreparation: 'తయారీ అవసరం',
  unknown: 'తెలియదు',
  notRequired: 'అవసరం లేదు',
  reusableDocuments: 'పునర్వినియోగ పత్రాలు',
  applicationSpecificDocuments: 'పథక-నిర్దిష్ట పత్రాలు',
  viewDocumentCenter: 'పత్రాల కేంద్రాన్ని వీక్షించండి →',
  privacyGuarantee: 'సురక్షితం మరియు గోప్యమైనది: యోజనా సేతు గుర్తింపు సంఖ్యలు, పాస్‌వర్డ్‌లు లేదా బ్యాంక్ వివరాలను ఎప్పుడూ అడగదు; నిల్వకు ముందు సున్నితమైన గుర్తింపులను శుభ్రపరుస్తుంది.',

  // Follow-ups
  followUpsTitle: 'రాబోయే రిమైండర్‌లు',
  userReminderBadge: 'వినియోగదారు రిమైండర్',
  officialDeadlineBadge: 'అధికారిక గడువు',
  today: 'ఈ రోజు',
  noFollowUps: 'రాబోయే రిమైండర్‌లు ఏవీ షెడ్యూల్ చేయబడలేదు.',
  viewAllFollowUps: 'అన్నీ చూడండి →',
  addReminder: '+ రిమైండర్ జోడించండి',

  // Trust & Data Freshness
  trustTitle: 'విశ్వసనీయత & డేటా తాజాదనం',
  recentlyVerified: 'ఇటీవల ధృవీకరించబడింది',
  officialSources: 'అధికారిక ప్రభుత్వ పోర్టల్స్',
  nodalSources: 'చట్టబద్ధమైన నోడల్ ఏజెన్సీలు',
  needsVerification: 'ధృవీకరణ పెండింగ్‌లో ఉంది',
  verifiedOfficialBadge: 'ధృవీకరించబడిన అధికారిక సైట్',
  knownNodalBadge: 'గుర్తింపు పొందిన నోడల్ వేదిక',
  unverifiedBadge: 'బాహ్య మూలం',
  statutoryAuditNotice: 'గెజిట్‌లు మరియు విభాగ నోటిఫికేషన్‌ల ప్రకారం తనిఖీ చేయబడింది.',

  // Profile & Assessment
  profileCompleteness: 'ప్రొఫైల్ సమగ్రత',
  missingFieldsAlert: 'సమాచారం అసంపూర్ణంగా ఉంది.',
  completeProfilePrompt: 'మీ ప్రొఫైల్‌ను పూర్తి చేయడం ద్వారా సిఫార్సుల ఖచ్చితత్వం పెరుగుతుంది.',
  completeProfileBtn: 'ప్రొఫైల్‌ను పూర్తి చేయండి →',
  editProfile: 'ప్రొఫైల్ సవరించండి',

  // Empty & Fallback States
  welcomeTitle: 'యోజనా సేతుకు స్వాగతం',
  welcomeSubtitle: 'వ్యక్తిగతీకరించిన పథక సిఫార్సులను పొందడానికి మీ వ్యాపారం గురించి మాకు తెలియజేయండి.',
  buildProfileBtn: 'వ్యాపార ప్రొఫైల్‌ను సృష్టించండి →',
  noMatchTitle: 'ఇంకా బలమైన సరిపోలికలు లభించలేదు',
  noMatchSubtitle: 'ప్రస్తుత సమాచారంతో మేము ఎటువంటి అధిక-విశ్వసనీయ పథకాన్ని గుర్తించలేకపోయాము.',
  reviewProfileBtn: 'ప్రొఫైల్‌ను సమీక్షించండి',
  exploreSupportBtn: 'మద్దతు రంగాలను అన్వేషించండి',
  viewNearMatchesBtn: 'సమీప సరిపోలికలను చూడండి',

  // Modals & Actions
  close: 'మూసివేయి',
  save: 'భద్రపరచు',
  saved: 'భద్రపరచబడింది',
  confirmSubmissionTitle: 'అధికారిక పోర్టల్ సమర్పణను నిర్ధారించండి',
  confirmSubmissionNotice: 'ముఖ్య గమనిక: అధికారిక పోర్టల్ తెరవడం ద్వారా మీ దరఖాస్తు స్వయంచాలకంగా సమర్పించబడదు. మీరు వారి సైట్‌లో ప్రభుత్వ ప్రక్రియను పూర్తి చేయాలి.',
  confirmSubmissionQuestion: 'మీరు అధికారిక పోర్టల్‌లో మీ దరఖాస్తును పూర్తి చేసి సమర్పించారా?',
  confirmYes: 'అవును, నేను సమర్పించాను',
  confirmNo: 'ఇంకా లేదు, ఇంకా సిద్ధమవుతున్నాను',
  portalAcknowledgedPrompt: 'అధికారిక రసీదు సంఖ్యను నమోదు చేయండి (ఐచ్ఛికం):',

  // Dashboard 2.0 — Entrepreneur Command Center
  dashSubtitle: 'మీ దృష్టి అవసరమైనవి ఇక్కడ ఉన్నాయి.',
  dashIndicatorReadiness: 'ప్రొఫైల్ సన్నద్ధత',
  dashIndicatorActions: 'పెండింగ్ పనులు',
  dashIndicatorApplications: 'క్రియాశీల దరఖాస్తులు',
  dashIndicatorSaved: 'సేవ్ చేసిన పథకాలు',
  dashContinueJourney: 'ఆపిన చోట నుండి కొనసాగించండి →',
  dashExploreMatches: 'నా సరిపోలికలను చూడండి →',
  dashOpportunitiesTitle: 'అగ్ర అవకాశాలు',
  dashWhyMatches: 'ఇది ఎందుకు సరిపోతుంది',
  dashViewScheme: 'పథకాన్ని చూడండి →',
  dashPotentiallyRelevant: 'సంబంధితంగా ఉండవచ్చు',
  dashJourneyTitle: 'నా ప్రయాణం',
  dashCurrentStage: 'ప్రస్తుత దశ',
  dashStageDISCOVER: 'కనుగొనండి',
  dashStageMATCH: 'సరిపోల్చండి',
  dashStageUNDERSTAND: 'అర్థం చేసుకోండి',
  dashStagePREPARE: 'సిద్ధం చేయండి',
  dashStageAPPLY: 'దరఖాస్తు చేయండి',
  dashStageTRACK: 'ట్రాక్ చేయండి',
  dashStageLineDISCOVER: 'సంబంధిత ప్రభుత్వ మద్దతును కనుగొనడానికి మీ వ్యాపారం గురించి చెప్పండి.',
  dashStageLineMATCH: 'మీ ప్రొఫైల్ ధృవీకరించబడిన పథకాలతో సరిపోల్చబడింది.',
  dashStageLineUNDERSTAND: 'ప్రతి పథకం ఏమి ఇస్తుందో, ఏమి అడుగుతుందో సమీక్షించండి.',
  dashStageLinePREPARE: 'దరఖాస్తు చేసే ముందు మీ పత్రాలు, వివరాలు సేకరించండి.',
  dashStageLineAPPLY: 'మీ దరఖాస్తులు కొనసాగుతున్నాయి.',
  dashStageLineTRACK: 'సమర్పించిన దరఖాస్తులను ఇక్కడ ట్రాక్ చేయండి.',
  dashCtaDISCOVER: 'పథకం సరిపోలికతో ప్రారంభించండి →',
  dashCtaMATCH: 'మీ సరిపోలికలను సమీక్షించండి →',
  dashCtaUNDERSTAND: 'మీ సరిపోలికలను అన్వేషించండి →',
  dashCtaPREPARE: 'సన్నద్ధతను కొనసాగించండి →',
  dashCtaAPPLY: 'దరఖాస్తులను చూడండి →',
  dashCtaTRACK: 'దరఖాస్తులను ట్రాక్ చేయండి →',
  dashPrepTitle: 'సన్నద్ధతా కేంద్రం',
  dashPrepDocuments: 'పత్రాలు',
  dashPrepFinancial: 'ఆర్థిక ప్రొఫైల్',
  dashPrepRegistrations: 'వ్యాపార నమోదులు',
  dashPrepPortal: 'అధికారిక సమర్పణ',
  dashPrepComplete: 'పూర్తి',
  dashPrepAttention: 'శ్రద్ధ అవసరం',
  dashPrepNotAssessed: 'ఇంకా అంచనా వేయలేదు',
  dashPrepPortalAvailable: 'అధికారిక పోర్టల్ అందుబాటులో ఉంది',
  dashPrepOpenWorkspace: 'సన్నద్ధతా కార్యస్థలాన్ని తెరవండి →',
  dashApplicationsTitle: 'దరఖాస్తులు',
  dashApplicationsEmpty: 'మీరు సిద్ధం చేయడం ప్రారంభించే దరఖాస్తులు ఇక్కడ కనిపిస్తాయి.',
  dashViewApplications: 'దరఖాస్తులను చూడండి →',
  dashExploreYourMatches: 'మీ సరిపోలికలను అన్వేషించండి →',
  dashSavedTitle: 'సేవ్ చేసిన పథకాలు',
  dashSchemesSaved: 'పథకాలు సేవ్ చేయబడ్డాయి',
  dashSavedEmpty: 'మీరు ఇంకా ఏ పథకాన్ని సేవ్ చేయలేదు.',
  dashViewAllSaved: 'సేవ్ చేసిన అన్ని పథకాలను చూడండి →',
  dashReadinessTitle: 'ప్రొఫైల్ సన్నద్ధత',
  dashReadinessPersonal: 'వ్యక్తిగత',
  dashReadinessBusiness: 'వ్యాపార',
  dashReadinessFinancial: 'ఆర్థిక',
  dashReadinessRegistrations: 'నమోదులు',
  dashReadinessDocuments: 'పత్రాలు',
  dashStateComplete: 'పూర్తి',
  dashStateAttention: 'శ్రద్ధ అవసరం',
  dashStateNotAssessed: 'ఇంకా అంచనా వేయలేదు',
  dashCompleteProfile: 'ప్రొఫైల్ పూర్తి చేయండి →',
  dashTrustTitle: 'డేటా & నమ్మకం',
  dashTrustBasedOn: 'సిఫార్సులు వీటిపై ఆధారపడి ఉన్నాయి:',
  dashTrustProfile: 'మీ ప్రొఫైల్',
  dashTrustDeterministic: 'నిర్ణయాత్మక సరిపోలిక',
  dashTrustSource: 'పథక మూల సమాచారం',
  dashActivityTitle: 'ఇటీవలి కార్యాచరణ',
  dashReadinessIntro: 'ఐదు రంగాల్లో మీ ప్రొఫైల్ యొక్క త్వరిత వీక్షణ.',
  dashViewProfile: 'ప్రొఫైల్ చూడండి →',
  dashActivityEmpty: 'మీరు ప్రారంభించగానే మీ ఇటీవలి కార్యాచరణ ఇక్కడ కనిపిస్తుంది.',
  dashRemoveSaved: 'సేవ్ చేసిన వాటి నుండి తొలగించు',
  dashTrustIntro: 'మీ అగ్ర అవకాశాల కోసం విశ్వాస సంకేతాలు, పథక మూలం నుండి ధృవీకరించబడ్డాయి.',
};
