export const INDIAN_STATES: string[] = [
  'All States & UTs',
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Delhi (NCT)',
  'Jammu & Kashmir',
  'Ladakh',
  'Puducherry',
];

export const SOUTH_INDIAN_STATES = [
  'Karnataka',
  'Kerala',
  'Tamil Nadu',
  'Telangana',
  'Andhra Pradesh',
] as const;

export type SouthIndianState = (typeof SOUTH_INDIAN_STATES)[number];
